### ISSUE TITLE
Deno package!

### ISSUE THREAD

**Issue by dlorenc** [wolfi-dev/os#102]
**Description**

Deno just released and has full NPM compatibility now. Should we package that?

**Comment by Lunarequest** [comment]
Deno is written in rust it depends on  #93

**Comment by patflynn** [comment]
assigning to @amouat for prioritisation.

**Comment by amouat** [comment]
Yeah, this looks good. Please let me know if we're getting any user requests for this and I'll raise the priority.

**Comment by amouat** [comment]
Closing as completed.
