### ISSUE TITLE
Package Mongodb

### ISSUE THREAD

**Issue by dlorenc** [wolfi-dev/os#103]
**Description**

Packaging instructions here: https://github.com/mongodb/mongo/blob/master/docs/building.md

Requested here: https://twitter.com/tsaha/status/1592559223887781888

**Comment by dlorenc** [comment]
If the licensing will cause an issue we can definitely reconsider. It's available on DockerHub as both a library image and one maintained by upstream mongo: 
<img width="867" alt="image" src="https://user-images.githubusercontent.com/1714486/201986686-bfb3877d-6856-4a11-8d71-0e3dda817fa9.png">

**Comment by amouat** [comment]
I think separate repos probably makes sense. I'd like to understand exactly what would go in that repo and what the difference in support is though.

**Comment by patflynn** [comment]
@amouat any thoughts on whether we target this for this quarter or the next?  I'll file an issue for tracking an 'extras' repo.

**Comment by amouat** [comment]
Let me open an internal issue for tracking a MongoDB image.

Agree on putting this in an "extras" repo.

**Comment by amouat** [comment]
In the meantime, for anyone coming across this issue, my suggestion is to look into creating your own melange build for MongoDB that can be used locally.
