### ISSUE TITLE
gcc versions can't be installed side by side

### ISSUE THREAD

**Issue by dlorenc** [wolfi-dev/os#10560]
They all place libgcc_s.so in /usr/lib directly so they fight.

We might need to move that to a versioned directory and symlink it in with the "-default" pattern.

**Comment by kaniini** [comment]
This is not needed, the latest libgcc_s is ABI compatible with old ones.  Just delete the old ones.

**Comment by dlorenc** [comment]
apko and apk get angry, maybe we can just add a replaces clause then?

**Comment by kaniini** [comment]
In general we want the latest libgcc_s.  We can delete the old ones and just move libgcc_s into a subpackage.  Will try to find some time to do the refactoring this week.
