### ISSUE TITLE
Ruby 3.3 Bundler package seems broken

### ISSUE THREAD

**Issue by dbussink** [wolfi-dev/os#10619]
When installing the `ruby3.3-bundler` package, it installs in the following location:

```
ruby3.3-bundler-2.5.3-r0 contains:
usr/bin/bundle
usr/bin/bundler
usr/lib/ruby/gems/3.3.0+0/gems/bundler-2.5.3/bundler.gemspec
usr/lib/ruby/gems/3.3.0+0/gems/bundler-2.5.3/exe/bundle
usr/lib/ruby/gems/3.3.0+0/gems/bundler-2.5.3/exe/bundler
...
```

It shows here a version of `3.3.0+0` in the path, which is broken. It needs to be `3.3.0`. When I manually build the `ruby3.3-bundler` package from this repo though, it creates the correct paths, using `3.3.0`. So something here went wrong building it, but not sure what is the problem to be honest?

**Comment by ajayk** [comment]
ruby3.3-bundler was not bumped after the release version of ruby , this was built  previously on rc version of ruby 3.3 , let me know if the fix solves the issue
