### ISSUE TITLE
question: what is equivalent of libc6-dev in wolfi?

### ISSUE THREAD

**Issue by tuananh** [wolfi-dev/os#11429]
Which package is the equivalent of libc6-dev in Wolfi? I'm thinking glibc-dev but I'm not sure.
```[tasklist]
### Tasks
```

**Comment by ajayk** [comment]
yep glibc-dev  on wolfi/os is equivalent of libc6-dev 

here is a comparison of headers 
https://packages.debian.org/sid/amd64/libc6-dev/filelist and https://gist.github.com/ajayk/d39fa4316eeec1e8d149000c25ccdb4a

**Comment by tuananh** [comment]
Thanks
