### ISSUE TITLE
[Wolfi Package Request]: starship

### ISSUE THREAD

**Issue by castrojo** [wolfi-dev/os#11518]
### What software would you like us to add to wolfi-os. Ideally include a URL to the project and its source.

https://github.com/starship/starship

### which versions of the software should we include?

Whatever the latest is, currently: v1.17.1

### Add some justification for why this specific package and versions are important.

I use wolfi as my cli environment in a container and I think having nicer interactive tools would be awesome.

### Please check all that apply

- [X] This package has an un-restrictive license
- [X] The package/versions proposed are actively maintained upstream
- [ ] I am interested in adding this package to Wolfi OS myself
- [ ] I am willing to help maintain this package

**Comment by ajayk** [comment]
https://github.com/wolfi-dev/os/pull/11520
