### ISSUE TITLE
mysql-client

### ISSUE THREAD

**Issue by mpanov** [wolfi-dev/os#11578]
### What software would you like us to add to wolfi-os. Ideally include a URL to the project and its source.

Example of the available package library:
https://pkgs.alpinelinux.org/packages?name=mysql-client&branch=v3.17&repo=&arch=x86_64&maintainer=

### which versions of the software should we include?

latest

### Add some justification for why this specific package and versions are important.

MySQL Client library is needed to connect with Cloud SQL DB

### Please check all that apply

- [X] This package has an un-restrictive license
- [X] The package/versions proposed are actively maintained upstream
- [ ] I am interested in adding this package to Wolfi OS myself
- [ ] I am willing to help maintain this package

**Comment by tuananh** [comment]
this looks like a dummy, empty package on alpine

> Dummy package for mysql-client migration

**Comment by dmdhrumilmistry** [comment]
is there any workaround to install this package on wolfi? 

I need this package in the image for installing python dependency [pymsqlclient](https://github.com/PyMySQL/mysqlclient)
