### ISSUE TITLE
[Wolfi Package Request]: Atuin

### ISSUE THREAD

**Issue by castrojo** [wolfi-dev/os#11615]
### What software would you like us to add to wolfi-os. Ideally include a URL to the project and its source.

https://github.com/atuinsh/atuin

### which versions of the software should we include?

latest

### Add some justification for why this specific package and versions are important.

Synced shell history is useful in an interactive wolfi session.

### Please check all that apply

- [X] This package has an un-restrictive license
- [X] The package/versions proposed are actively maintained upstream
- [ ] I am interested in adding this package to Wolfi OS myself
- [ ] I am willing to help maintain this package

**Comment by ajayk** [comment]
fixed by https://github.com/wolfi-dev/os/pull/11629
