### ISSUE TITLE
keycloak: where should we keep keycloak ?

### ISSUE THREAD

**Issue by tuananh** [wolfi-dev/os#1163]
when running, keycloak needs write permission in `/usr/share/java/keycloak-<version>/...`

https://github.com/wolfi-dev/os/blob/main/keycloak.yaml#L43

I'm not sure if it's good practice to make `nonroot` user own that path?

the official keycloak image (quay.io/keycloak/keycloak) use `/opt/keycloak/`

@dlorenc wdyt?

**Comment by dlorenc** [comment]
IMO that would go in the image configuration not in the package itself.

**Comment by tuananh** [comment]
i dont get it. how do we do that in image?

**Comment by dlorenc** [comment]
Something like this: https://github.com/chainguard-images/images/blob/0e950988ccb321b5254f2fcecf5e49496ca5e6db/images/node/configs/19.apko.yaml#L15
