### ISSUE TITLE
[Wolfi Package Request]: apr-util

### ISSUE THREAD

**Issue by bgermann** [wolfi-dev/os#12543]
### What software would you like us to add to wolfi-os. Ideally include a URL to the project and its source.

Apache Portable Runtime Utility: https://apr.apache.org/
Download source: https://apr.apache.org/download.cgi
Also available as Alpine package apr-util.

### which versions of the software should we include?

Latest

### Add some justification for why this specific package and versions are important.

This is a required dependency of subversion: #12486

### Please check all that apply

- [X] This package has an un-restrictive license
- [X] The package/versions proposed are actively maintained upstream
- [X] I am interested in adding this package to Wolfi OS myself
- [ ] I am willing to help maintain this package

**Comment by ajayk** [comment]
This package already exists as [libapr](https://github.com/wolfi-dev/os/blob/main/libapr.yaml)

**Comment by bgermann** [comment]
No, but libapr is available on the same website. apr-utils depends on libapr.
