### ISSUE TITLE
[Wolfi Package Request]: mods and glow

### ISSUE THREAD

**Issue by castrojo** [wolfi-dev/os#13254]
### What software would you like us to add to wolfi-os. Ideally include a URL to the project and its source.

https://github.com/charmbracelet/mods
https://github.com/charmbracelet/glow

mods lets you pipe commands through openai/localai via the command line or a pipeline. glow then formats the results into markdown. 

### which versions of the software should we include?

latest

### Add some justification for why this specific package and versions are important.

This is admittedly demo candy. 😄 

### Please check all that apply

- [X] This package has an un-restrictive license
- [X] The package/versions proposed are actively maintained upstream
- [ ] I am interested in adding this package to Wolfi OS myself
- [ ] I am willing to help maintain this package

**Comment by kranurag7** [comment]
@castrojo the issue was closed early because I referenced this issue in mods PR _(Fixes #)_ `glow` is added now via #13312 

_Enjoy reading markdown with ease :)_
