### ISSUE TITLE
CVE package scan and ABI compatibility checks fail for single arch package.

### ISSUE THREAD

**Issue by smoser** [wolfi-dev/os#13508]
https://github.com/wolfi-dev/os/pull/13321 exposed an issue in 2 c-i stages with a single-arch package.

* [Scan packages for CVEs](https://github.com/wolfi-dev/os/actions/runs/7991918538/job/21833043879#logs)
* [ABI Compatibility check](https://github.com/wolfi-dev/os/actions/runs/7991918538/job/21833044112#logs)

**Comment by srishtih** [comment]
Running into the same issue with this PR for openmpi https://github.com/wolfi-dev/os/pull/13394

**Comment by ajayk** [comment]
This has been resolved by https://github.com/wolfi-dev/os/pull/13509
