### ISSUE TITLE
[Wolfi Package Request]: apache2

### ISSUE THREAD

**Issue by mschoettle** [wolfi-dev/os#13726]
### What software would you like us to add to wolfi-os. Ideally include a URL to the project and its source.

The Apache HTTPD Server (Apache2): https://httpd.apache.org/

Download source: https://httpd.apache.org/download.cgi

It is also available as Alpine package `apache2`.

### which versions of the software should we include?

Latest version (2.4.58)

### Add some justification for why this specific package and versions are important.

This would be helpful to switch from the default `php-apache` images to an image with PHP and Apache2 from Wolfi.

### Please check all that apply

- [X] This package has an un-restrictive license
- [X] The package/versions proposed are actively maintained upstream
- [X] I am interested in adding this package to Wolfi OS myself
- [ ] I am willing to help maintain this package

**Comment by roaksoax** [comment]
Closing this issue as apache2 is now packaged.
