### ISSUE TITLE
[Wolfi Package Request]: openblas update to 0.3.26

### ISSUE THREAD

**Issue by xnox** [wolfi-dev/os#14441]
### What software would you like us to add to wolfi-os. Ideally include a URL to the project and its source.

https://github.com/OpenMathLib/OpenBLAS/releases/tag/v0.3.26 is available but i don't see update happening to it

### which versions of the software should we include?

0.3.26

### Add some justification for why this specific package and versions are important.

speed

### Please check all that apply

- [X] This package has an un-restrictive license
- [X] The package/versions proposed are actively maintained upstream
- [X] I am interested in adding this package to Wolfi OS myself
- [X] I am willing to help maintain this package

**Comment by xnox** [comment]
Why is https://github.com/wolfi-dev/os/blob/main/openblas.yaml not getting a pull request for an autobump?

**Comment by ajayk** [comment]
@stormqueen1990 fixed this in https://github.com/wolfi-dev/os/pull/14443
