### ISSUE TITLE
[Wolfi Package Request]: coredns

### ISSUE THREAD

**Issue by ameukam** [wolfi-dev/os#1458]
### What software would you like us to add to wolfi-os. Ideally include a URL to the project and its source.

Coredns: https://github.com/coredns/coredns

### which versions of the software should we include?

1.10

### Please check all that apply

- [X] This package has an un-restrictive license
- [X] The package/versions proposed are actively maintained upstream
- [X] I am interested in adding this package to Wolfi OS myself
- [ ] I am willing to help maintain this package

**Comment by rawlingsj** [comment]
Thanks for the issue @ameukam!  I believe there's already someone working on a coredns package.  I'll double check and update the issue but I think we should be able to get this in soon!

**Comment by ajayk** [comment]
cordons was added by https://github.com/wolfi-dev/os/pull/2217
