### ISSUE TITLE
building main repository's glibc and gcc using bootstrap-stage3

### ISSUE THREAD

**Issue by VasiliyS** [wolfi-dev/os#15477]
Hi there!

I'm trying to build the basic set of packages for `s390x`. So far I was able to successfully get through `stage1` to `stage 3`.

However, as a I start building the packages from the main `os` repository I run into issue as soon as I build `glibc` :  `gcc` stops to work ( `configure` complains that that C compile doesn't work - `ld` apparently can't find  `libc`).

What's the proper procedure? I took a look at your gh-actions and there doesn't seem to be a special workaround to rebuild packages around the new `glibc`... Well, `wolfictl` does build a graph, but it doesn't seem to take into account the acrobatics needed to move to both the new `glibc`.

Would really appreciate any pointers! Thank you for a super cool effort, BTW.

**Comment by VasiliyS** [comment]
OK, after some additional tinkering, it seems that the proper procedure is to build the new `wolfi-baselayout` first and then the new `glibc`.  Then packages continue to build in the sequence `wolfictl` suggests. However, the `wolfi-baselayout` package symlinks `lib64` to `lib`, which conflicts with the `wolfi-baselayout` package. Which is seen first when I try to compile `mprf` ( I try to build a subset of packages, not the whole repo).

Any practical advice on how to overcome this? Should I just comment out the symlinking part in `wolfi-baselayout`?

**Comment by ajayk** [comment]
@imjasonh / @jonjohnsonjr  : ^^

**Comment by kaniini** [comment]
Originally, Wolfi was not bootstrapped using wolfictl, and I solved the dependency order by hand.  In general you probably want to follow the order that is shown in Linux From Scratch for the base system.

**Comment by VasiliyS** [comment]
Thanks a lot!  @kaniini - yeah, I've actually followed the logic in the `Makefile` of the `bootstrap-stage3`. Which seems to work fine. The only two hiccups are:
- build `wolfi-baselayout` first, *but* remove the `lib64` to `lib` symlinking there. So far it didn't cause any issues anywhere.
- then `glibc` then all the base packages ( as in LFS or in the stage3)

for `s390x` there are  few minor adjustments needed in some packages ( e.g. `perl` based config requires different name for the target, etc).

I can build images with `apko` and run them. super cool!
Let me know if there's interest in supporting the `s390x` architecture in the official repo.
