### ISSUE TITLE
openjdk-17.yaml "default-jvm"

### ISSUE THREAD

**Issue by joepetrillo** [wolfi-dev/os#15513]
I could be misunderstanding how this is supposed to be working, but the openjdk-17 package does not set the JAVA_HOME variable and none of the jdk related programs in /usr/bin are recognized because the "default-jvm" folder they are linked to does not exist. In openjdk-17, for example, the folder it is installed to is really `/usr/lib/jvm/java-17-openjdk`.

![image](https://github.com/wolfi-dev/os/assets/32227357/d7e74ce9-80c6-4512-bbe4-72fbd7be5bd3)

To work around this, I have done the following in my dockerfile, is this correct/expected? I am using this dockerfile to build images application teams can use for Java 8, 11, and 17. I set the `JAVA_VERSION` arg to 17, and the `JAVA_HOME` arg to `/usr/lib/jvm/java-17-openjdk` and this seems to work.

![image](https://github.com/wolfi-dev/os/assets/32227357/206c8f42-cee7-4786-ae6c-988975596133)

**Comment by ajayk** [comment]
there is `openjdk-17-default-jvm`  package available for this high sets the default-jvm 

```
/ # apk add openjdk-17
fetch https://packages.wolfi.dev/os/aarch64/APKINDEX.tar.gz
(1/18) Installing libbrotlicommon1 (1.1.0-r1)
(2/18) Installing libbrotlidec1 (1.1.0-r1)
(3/18) Installing libbz2-1 (1.0.8-r6)
(4/18) Installing libpng (1.6.43-r0)
(5/18) Installing freetype (2.13.2-r2)
(6/18) Installing fontconfig-config (2.15.0-r0)
(7/18) Installing libexpat1 (2.6.2-r0)
(8/18) Installing libfontconfig1 (2.15.0-r0)
(9/18) Installing ca-certificates (20240315-r0)
(10/18) Installing libffi (3.4.6-r0)
(11/18) Installing libtasn1 (4.19.0-r1)
(12/18) Installing p11-kit (0.25.3-r1)
(13/18) Installing p11-kit-trust (0.25.3-r1)
(14/18) Installing java-cacerts (20230106-r3)
(15/18) Installing java-common (0.1-r1)
(16/18) Installing openjdk-17-jre-base (17.0.10-r1)
(17/18) Installing openjdk-17-jre (17.0.10-r1)
(18/18) Installing openjdk-17 (17.0.10-r1)
OK: 215 MiB in 32 packages
/ # java
sh: java: not found
/ # apk add openjdk-17-default-jvm
(1/1) Installing openjdk-17-default-jvm (17.0.10-r1)
OK: 215 MiB in 33 packages
/ # java --version 
openjdk 17.0.10-internal 2024-01-16
OpenJDK Runtime Environment (build 17.0.10-internal+0-wolfi-r1)
OpenJDK 64-Bit Server VM (build 17.0.10-internal+0-wolfi-r1, mixed mode, sharing)
```

**Comment by joepetrillo** [comment]
Oh ok, so thats one of the subpackages it seems like (missed those). `openjdk-17-default-jdk` is another option, but I am not exactly sure what the difference is. Do we only need to install `openjdk-17-default-jvm` or should we install `openjdk-17` and then `openjdk-17-default-jvm`

**Comment by ajayk** [comment]
check the runtimes here for [openjdk-17-default-jvm](https://github.com/wolfi-dev/os/blob/main/openjdk-17.yaml#L199-L203) , it gets you openjdk-17-jre and sets the default jvm 


and [openjdk-17-default-jdk](https://github.com/wolfi-dev/os/blob/main/openjdk-17.yaml#L212C12-L217) , it gets you openjdk-17-jre, openjdk-17 and  sets the default jvm
