### ISSUE TITLE
NodeJS 16 NPM Version Warning

### ISSUE THREAD

**Issue by joepetrillo** [wolfi-dev/os#15551]
When using the `nodejs-16` package, since the bundled npm is not used, we get a warning that version `10.5.0` of npm does not support node 16. However, things seem to install correctly for me. Is this safe to ignore? What was the reason not to use the bundled npm that comes with each node version? Thanks!

`# npm WARN cli npm v10.5.0 does not support Node.js v16.20.2. This version of npm supports the following node versions: ^18.17.0 || >=20.5.0.`

**Comment by ajayk** [comment]
Please use latest  LTS versions version of nodejs-20,  https://endoflife.date/nodejs , we don't have support for non latest versions or EOL versions of nodejs on wolfi
