### ISSUE TITLE
[Wolfi Package Request]: kubernetes-csi-node-driver-registrar 2.10

### ISSUE THREAD

**Issue by fraenkel** [wolfi-dev/os#15705]
### What software would you like us to add to wolfi-os. Ideally include a URL to the project and its source.

kubernetes-csi-node-driver-registrar 2.10

### which versions of the software should we include?

2.10

### Add some justification for why this specific package and versions are important.

You already have 2.9.3 but no updates for 2.10

### Please check all that apply

- [X] This package has an un-restrictive license
- [X] The package/versions proposed are actively maintained upstream
- [ ] I am interested in adding this package to Wolfi OS myself
- [ ] I am willing to help maintain this package

**Comment by tuananh** [comment]
already available at https://github.com/wolfi-dev/os/blob/main/kubernetes-csi-node-driver-registrar-2.10.yaml

Should close this
