### ISSUE TITLE
[Wolfi Package Request]: Dart

### ISSUE THREAD

**Issue by dlorenc** [wolfi-dev/os#159]
### What software would you like us to add to wolfi-os. Ideally include a URL to the project and its source.

Dart: https://github.com/dart-lang/

### Please check all that apply

- [x] This package has an un-restrictive license
- [ ] I am interested in adding this package to Wolfi OS myself.
- [ ] I am willing to help maintain this package.

**Comment by kaniini** [comment]
Sure, we should do it!
