### ISSUE TITLE
[Wolfi Package Request]: Helix version 24.3

### ISSUE THREAD

**Issue by storopoli** [wolfi-dev/os#16094]
### What software would you like us to add to wolfi-os. Ideally include a URL to the project and its source.

Helix: https://github.com/helix-editor/helix

### which versions of the software should we include?

24.3

### Add some justification for why this specific package and versions are important.

Helix is a vim-inspired Rust terminal editor.
Project homepage: https://helix-editor.com/
GitHub (23k stars): https://helix-editor.com/

Here's how Alpine packages it: https://git.alpinelinux.org/aports/tree/community/helix?h=master

### Please check all that apply

- [X] This package has an un-restrictive license
- [X] The package/versions proposed are actively maintained upstream
- [ ] I am interested in adding this package to Wolfi OS myself
- [X] I am willing to help maintain this package

**Comment by ajayk** [comment]
Fixed by https://github.com/wolfi-dev/os/pull/16073

**Comment by storopoli** [comment]
Thank you!
