### ISSUE TITLE
[Wolfi Package Request]: musl-dev

### ISSUE THREAD

**Issue by dmdhrumilmistry** [wolfi-dev/os#16117]
### What software would you like us to add to wolfi-os. Ideally include a URL to the project and its source.

musl-dev

https://pkgs.alpinelinux.org/package/edge/main/aarch64/musl-dev
https://pkgs.alpinelinux.org/package/edge/main/x86_64/musl-dev

### which versions of the software should we include?

1.2.5

### Add some justification for why this specific package and versions are important.

Many Python packages rely on C compilation, which necessitates the installation of `musl-dev`. Without this package, users may encounter difficulties installing dependencies that require C compilation.

### Please check all that apply

- [x] This package has an un-restrictive license
- [x] The package/versions proposed are actively maintained upstream
- [ ] I am interested in adding this package to Wolfi OS myself
- [ ] I am willing to help maintain this package

**Comment by kaniini** [comment]
On Alpine, you should use build-base, which is available also on Wolfi.  Wolfi uses glibc, too, not musl.

**Comment by dmdhrumilmistry** [comment]
Thanks. I was able to fix issue by install `glibc-dev`.
