### ISSUE TITLE
[Wolfi Package Request]: icu-libs & icu-data-full

### ISSUE THREAD

**Issue by sheldonhull** [wolfi-dev/os#16333]
### What software would you like us to add to wolfi-os. Ideally include a URL to the project and its source.

icu-libs and icu-data-full is needed for localization support.

### which versions of the software should we include?

latest

### Add some justification for why this specific package and versions are important.

I see this mentioned in another issue https://github.com/dotnet/dotnet-docker/issues/3844.

I want to use the minimal aspnet image, but it seems this is a requirement for the base image to properly support localization. If I'm missing a better way to include this please let me know, since newer to the Wolfi OS project itself.

### Please check all that apply

- [X] This package has an un-restrictive license
- [X] The package/versions proposed are actively maintained upstream
- [ ] I am interested in adding this package to Wolfi OS myself
- [ ] I am willing to help maintain this package

**Comment by sheldonhull** [comment]
@tuananh thanks for getting that started 💯 subscribed and will keep an eye out for any questions. cheers

**Comment by rcollette** [comment]
Active chainguard customer, looking to add .NET to our licensing, but this is a blocker for us.
