### ISSUE TITLE
[Wolfi Package Request]: syft v0.98.0

### ISSUE THREAD

**Issue by Adar-Checkmarx** [wolfi-dev/os#16609]
### What software would you like us to add to wolfi-os. Ideally include a URL to the project and its source.

https://github.com/anchore/syft/releases/tag/v0.98.0

### which versions of the software should we include?

0.98.0, 0.83.0

### Add some justification for why this specific package and versions are important.

the latest syft version (1.x.x) breaks my app :)

### Please check all that apply

- [X] This package has an un-restrictive license
- [X] The package/versions proposed are actively maintained upstream
- [ ] I am interested in adding this package to Wolfi OS myself
- [ ] I am willing to help maintain this package

**Comment by ajayk** [comment]
Closing this as there is a way to get `syft v0.98.0 ` installed
