### ISSUE TITLE
Validate the java compilation flags.

### ISSUE THREAD

**Issue by vaikas** [wolfi-dev/os#18747]
While debugging build failures in #18667 noticed there were some warnings about flags being ignored, they should be investigated and fixed as necessary:

```
2024/05/06 22:12:06 INFO The following warnings were produced. Repeated here for convenience:
2024/05/06 22:12:06 INFO WARNING: Ignoring CFLAGS(-O2 -Wall -fomit-frame-pointer -march=x86-64-v2 -mtune=broadwell) found in environment. Use --with-extra-cflags
2024/05/06 22:12:06 INFO WARNING: Ignoring CXXFLAGS(-O2 -Wall -fomit-frame-pointer -march=x86-64-v2 -mtune=broadwell) found in environment. Use --with-extra-cxxflags
2024/05/06 22:12:06 INFO WARNING: Ignoring LDFLAGS(-Wl,--as-needed,-O1,--sort-common -Wl,-z,relro,-z,now,-z,noexecstack) found in environment. Use --with-extra-ldflags
```

**Comment by vaikas** [comment]
Ok, so I can hackily make this actually use the flags, even though the warnings are present.

If I add the following lines to the `autoconf/configure` step:
```
        --with-extra-cflags="$CFLAGS" \
        --with-extra-cxxflags="$CXXFLAGS" \
        --with-extra-ldflags="$LDFLAGS" \
```

I can see that configure step runs with them, and when I compile, I can see there bunch more warnings that are not present when running without them.

However, the warning is still present, since there's really no way to `unset` those variables. I tried to set them to something else in the environment.environment block, then unsetting these, but that didn't work, or I did it wrong.

I tried to also use env variables to set them in the vars section, but that didn't really work, and it would still leave the warnings still present.

Another option would be to maintain another env file, like: jdk-{arch}.env file, with these variables having different names than:
https://github.com/wolfi-dev/os/blob/98ee15bd021c2299bbb372b2cd771cce0d6986bc/build-x86_64.env#L1

But this has two downsides at the moment. We would have to hack the Makefile to then override the hardcoded env files here:
https://github.com/wolfi-dev/os/blob/main/Makefile#L18

I am curious if there are other cases where one would want to use a different set of env variables (not additive)

 * Am I missing something obvious in making changes to the env vars, or how to override values in them, or creating easily maintainable parallel env files?
 * I need to verify that the resulting binary actually has been produced with all the right flags. Like I said, I can see plenty more variables, but would be nice to validate the other flags taking effect. I just don't know how to do this.

**Comment by xnox** [comment]
Lots of packages sed/replace/re-export vars.

In every pipeline in every runs: portion.

But also, if the environment variable is ignored, they are harmless.

We have a few upstream packages that ignore them.

Separately we probably should sync and export these hardening flags in our gcc image too btw.

**Comment by vaikas** [comment]
Do you have an example for the configure? I know I can drop to shell instead of the pipeline, but that just seems like another workaround? That's where I need to run it as.
Just to be clear , I tried something like:
pipeline:
  - runs: |
       # muck with the env variables
  - uses: autoconf/configure
    with:
 
And the first step changes to env does not "stick". Is that what you meant?

**Comment by vaikas** [comment]
I get it that they are harmless, but I just think it's icky to have unnecessary warnings.

**Comment by vaikas** [comment]
This actually should not have been marked as fixed since it wasn't completed for all versions of JDKs. I tried to state that in the PR descriptions that it addressed but did not fix. However, there's now a very specific error that I'm seeing on JDK 18 on x86_64, so I'll create a different issue to track that.
