### ISSUE TITLE
RFE: Test/quality request - Package installation should be tested as part of build.

### ISSUE THREAD

**Issue by smoser** [wolfi-dev/os#18871]
Package build should verify that a package is installable by doing an install.

Packages could be uninstallable if they have incorrect depends.

I don't have an example of a failing-to-install package.

**Comment by joshrwolf** [comment]
I think we already do this in presubmit: https://github.com/wolfi-dev/os/blob/main/.github/workflows/ci-build.yaml#L170

**Comment by smoser** [comment]
Hooray!
