### ISSUE TITLE
[Wolfi Package Request]: Erlang OTP 27

### ISSUE THREAD

**Issue by sando38** [wolfi-dev/os#20317]
### What software would you like us to add to wolfi-os. Ideally include a URL to the project and its source.

[Erlang 27 is released](https://github.com/erlang/otp/releases/tag/OTP-27.0) and it would be great to have that package available in wolfi-os as well 👍 
https://github.com/wolfi-dev/os/blob/main/erlang-26.yaml

### which versions of the software should we include?

27

### Add some justification for why this specific package and versions are important.

We are relying on the package for our XMPP server and want to benefit from the updates coming through Erlang 27. 
I can also adapt the existing `erlang-26.yaml` as a PR, if that helps 👍 

### Please check all that apply

- [X] This package has an un-restrictive license
- [X] The package/versions proposed are actively maintained upstream
- [ ] I am interested in adding this package to Wolfi OS myself
- [ ] I am willing to help maintain this package

**Comment by ajayk** [comment]
Automated version stream failed for Erlang-27 due to the inconsistent version number between the endoflife.date  and the Erlang tags 


```
2024-05-28 00:30:26.009 PDT
Creating version stream for erlang-26  

2024-05-28 00:30:26.010 PDT
attempting to bump version to 27.0.0

2024-05-28 00:30:26.011 PDT
processing fetch node:

2024-05-28 00:30:26.011 PDT
  uri: https://github.com/erlang/otp/releases/download/OTP-${{package.version}}/otp_src_${{package.version}}.tar.gz

2024-05-28 00:30:26.011 PDT
  evaluated: https://github.com/erlang/otp/releases/download/OTP-27.0.0/otp_src_27.0.0.tar.gz

2024-05-28 00:30:26.141 PDT
got 404 Not Found when fetching https://github.com/erlang/otp/releases/download/OTP-27.0.0/otp_src_27.0.0.tar.gz

2024-05-28 00:30:26.461 PDT
got 404 Not Found when fetching https://github.com/erlang/otp/releases/download/OTP-27.0.0/otp_src_27.0.0.tar.gz
```
