### ISSUE TITLE
Python 3.12 broken packages

### ISSUE THREAD

**Issue by yashgorana** [wolfi-dev/os#22273]
Some recent change made that makes `py3.12-pip` conflicts with `python-3.12-default`.
![image](https://github.com/wolfi-dev/os/assets/11070218/f6ea6a1e-e2a6-4bfb-a558-3510f22fdc36)

After digging around there seems to be a couple of changes that were made
- `python-3.12-default` was replaced with `python-3.12-base` (https://github.com/wolfi-dev/os/commit/48fc6ab2dc45a096ece8457639ef95853e7d43b7, https://github.com/wolfi-dev/os/pull/14943)
- an update `py3.12-pip` to requires `python-3.12-base` (likely this one https://github.com/wolfi-dev/os/commit/a2c8c0edb98a8a6a2affadfae9b5ff589fcdbbc4, https://github.com/wolfi-dev/os/pull/20318)

Earlier similar breaking change were made from `python-3.12` to `python-3.12-default`; where the former no longer had `python` as a valid executable only `python3.12`, and required the "default" suffix to get it to work. Same for -dev-default

Questions
1. Which package should we use to get a stable python3.12 + pip with "python" as a valid entrypoint? just python-3.12? python-3.12-base?
2. Can we have a stable package+version semantics that doesn't keep getting updated? That guarentees #1 without any conflicts? We've already had -default, -dev-default, -base?
3. Is there any place, other than Github PRs, where we can see what breaking changes are going to be introduced?

**Comment by xnox** [comment]
After python-3.12-default was added, and it was observed that it was breaking things..... it was withdrawn and was not updated anymore. And things reverted back to status quo of python-3.12 shippping all symlinks (and internally depending on python-3.12-base to allow coinstallable python installations).

`apk add python-3.12 py3.12-pip` is what still works, and used to work, apart from a brief hiatus with introduction and removal of python-3.12-default. Which is stable and continues to work....

Can you clarify how/why have you started to use python-3.12-default, given i thought we withdrew it everywhere as it was a non-starter.

When adding apk packages, do you use `--latest` flag? or `upgrade --latest`?

Note for container image reproducibility reasons we continue to publish obsolete package epochs even when  they are no longer used / shouldn't be used.

**Comment by xnox** [comment]
> python-3.12-default was replaced with python-3.12-base

Is not entirely accurate, python-3.12-default got reverted back to python-3.12 - as in the package that ships "python3 -> python3.12" symlink. It is true that python-3.12 depends on python-3.12-base which contains the bulk of the python stdlib. This is to allow co-installing multiple pythons during package building to support multiple python versions in parallel (i.e. to allow installing python-3.12-base and python-3.11-base at the same time, which didn't used to be possible).

The intention has always been to land that without any change to the top level package names or dependencies, which unfortunately we did get wrong in February for a brief period of time when -default introduced and withdrawn.

**Comment by xnox** [comment]
> Which package should we use to get a stable python3.12 + pip with "python" as a valid entrypoint?

If you want to access default/latest python3 and matching pip package for it one installs:

```
# apk add python3 py3-pip
```

Which resolves to:
```
(1/18) Installing libbz2-1 (1.0.8-r8)
(2/18) Installing libexpat1 (2.6.2-r1)
(3/18) Installing libffi (3.4.6-r2)
(4/18) Installing gdbm (1.23-r6)
(5/18) Installing xz (5.6.2-r0)
(6/18) Installing libgcc (13.2.0-r7)
(7/18) Installing libstdc++ (13.2.0-r7)
(8/18) Installing mpdecimal (4.0.0-r2)
(9/18) Installing ncurses-terminfo-base (6.4_p20231125-r3)
(10/18) Installing ncurses (6.4_p20231125-r3)
(11/18) Installing readline (8.2-r6)
(12/18) Installing sqlite-libs (3.45.1-r1)
(13/18) Installing python-3.12-base (3.12.4-r0)
(14/18) Installing py3.12-flit-core (3.9.0-r2)
(15/18) Installing py3.12-setuptools (70.0.0-r1)
(16/18) Installing py3.12-pip-base (24.0-r3)
(17/18) Installing py3.12-pip (24.0-r3)
(18/18) Installing python-3.12 (3.12.4-r0)
OK: 96 MiB in 32 packages
```

If you want explicit major version, one should install "python-3.12 py3.12-pip".

That has been the case all of this year and will continue to be so, apart from a brief hiatus in February/March.

**Comment by xnox** [comment]
https://github.com/wolfi-dev/os/actions/runs/9581608771/job/26420021936#step:15:574
