### ISSUE TITLE
[Wolfi Package Request]: async-profiler (Java)

### ISSUE THREAD

**Issue by lyoung-confluent** [wolfi-dev/os#23202]
### What software would you like us to add to wolfi-os. Ideally include a URL to the project and its source.

https://github.com/async-profiler/async-profiler

### which versions of the software should we include?

v3.0 (latest)

### Add some justification for why this specific package and versions are important.

async-profiler is a popular (~7.3k stars) tool for profiling Java processes at runtime. While it is used to profile Java applications, the tool itself is written primarily in CPP, it would be convenient to be able to install the tool via `apk add` to profile Java applications running on Wolfi

### Please check all that apply

- [X] This package has an un-restrictive license
- [X] The package/versions proposed are actively maintained upstream
- [X] I am interested in adding this package to Wolfi OS myself
- [ ] I am willing to help maintain this package

**Comment by ajayk** [comment]
thanks @lyoung-confluent 🎉  , this has been closed by #23203
