### ISSUE TITLE
Improve C/C++ compiler testing 

### ISSUE THREAD

**Issue by pnasrat** [wolfi-dev/os#23724]
The gcc-12 12.4.0 bump broke compilation due to missing dependencies

Ensure that our C/C++ compilers have adequate test pipelines to ensure compiling works

**Comment by smoser** [comment]
We can add a simple `test:` test that does a hello world test in C and C++, but I'm guessing that  gcc has a reasonable test suite .  We should probably consider running that in `test:` (rather than part of the build, so as to test dependencies).

**Comment by TaylorBloom129** [comment]
@pnasrat is this an interrupts / eng pri or backlog item?

**Comment by pnasrat** [comment]
@TaylorBloom129 @roaksoax asked me to file it more a backlog item though @xnox may have added some initial testing.

**Comment by xnox** [comment]
Related:
- https://github.com/wolfi-dev/os/pull/23720

**Comment by ZainUlAbidenBuriro** [comment]
Hello I want to learn cpp guide me pleaaase
