### ISSUE TITLE
[Wolfi Package Request]: `jmx_prometheus_javaagent`

### ISSUE THREAD

**Issue by marshall007** [wolfi-dev/os#24072]
### What software would you like us to add to wolfi-os. Ideally include a URL to the project and its source.

JMX Exporter for Prometheus: https://github.com/prometheus/jmx_exporter

### which versions of the software should we include?

0.17.2

### Add some justification for why this specific package and versions are important.

The `sonarqube` package has an implicit dependency on [`prometheus/jmx_exporter`](https://github.com/prometheus/jmx_exporter). When `prometheusExporter.enabled` is true, the official helm chart:

1. downloads `https://repo1.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/<version>/jmx_prometheus_javaagent-<version>.jar` (defaults to version `0.17.2`)
   - [`charts/sonarqube/templates/_helpers.tpl#L194-L203`](https://github.com/SonarSource/helm-chart-sonarqube/blob/20130c4ad62c65acf2d65dc1913e4cdb95381c12/charts/sonarqube/templates/_helpers.tpl#L194-L203)
1. ... and copies it to `/opt/sonarqube/data/jmx_prometheus_javaagent.jar`
   - [`charts/sonarqube/templates/_pod.tpl#L131-L155`](https://github.com/SonarSource/helm-chart-sonarqube/blob/20130c4ad62c65acf2d65dc1913e4cdb95381c12/charts/sonarqube/templates/_pod.tpl#L131-L155)
1. then sets sets JVM opts `-javaagent:/opt/sonarqube/data/jmx_prometheus_javaagent.jar=...`
   - [`charts/sonarqube/templates/_helpers.tpl#L158-L164`](https://github.com/SonarSource/helm-chart-sonarqube/blob/20130c4ad62c65acf2d65dc1913e4cdb95381c12/charts/sonarqube/templates/_helpers.tpl#L158-L164)

### Please check all that apply

- [X] This package has an un-restrictive license
- [ ] The package/versions proposed are actively maintained upstream
- [X] I am interested in adding this package to Wolfi OS myself
- [X] I am willing to help maintain this package

**Comment by lioneloh** [comment]
I already developed a package for our internal use with 1.0.1 version, but should work for any version. I can initiate a PR with it if needed.
