### ISSUE TITLE
[Wolfi Package Request]: distribution v2.8.3

### ISSUE THREAD

**Issue by sgalsaleh** [wolfi-dev/os#24322]
### What software would you like us to add to wolfi-os. Ideally include a URL to the project and its source.

https://github.com/distribution/distribution

### which versions of the software should we include?

v2.8.3

### Add some justification for why this specific package and versions are important.

The current available Wolfi package for `distribution` is based off of version 3.0.0, which is still in Beta. It would be great to have a Wolfi package that's based off of the latest official stable release (`v2.8.3`).

### Please check all that apply

- [X] This package has an un-restrictive license
- [X] The package/versions proposed are actively maintained upstream
- [X] I am interested in adding this package to Wolfi OS myself
- [X] I am willing to help maintain this package

**Comment by kranurag7** [comment]
Hey @sgalsaleh, I think following might be useful to you. It says only the latest version is supported and maintained. Given distribution is already bumped to beta release of 3.0.0 so I'm not sure about a downgrade here. 

Ref: https://edu.chainguard.dev/chainguard/chainguard-images/overview/#a-note-about-wolfi-packages

**Comment by tuananh** [comment]
ref: https://github.com/distribution/distribution/discussions/4404

**Comment by sgalsaleh** [comment]
That is helpful, thanks! I'll close this issue then. Appreciate the prompt feedback 🙏.
