### ISSUE TITLE
[Wolfi Package Request]: iptables-wrapper

### ISSUE THREAD

**Issue by sgalsaleh** [wolfi-dev/os#24440]
### What software would you like us to add to wolfi-os. Ideally include a URL to the project and its source.

https://github.com/kubernetes-sigs/iptables-wrappers/
https://raw.githubusercontent.com/kubernetes-sigs/iptables-wrappers/v2/iptables-wrapper-installer.sh

### which versions of the software should we include?

[v2](https://github.com/kubernetes-sigs/iptables-wrappers/releases/tag/v2)

### Add some justification for why this specific package and versions are important.

The wrapper script and the `iptables-wrapper` binary seem to be required to support ipv6 in kube-proxy. When trying to use the kube-proxy Wolfi package with just the `ip6tables` and `iptables` packages, kube-proxy complains with the following:
```bash
...
server_others.go:146] "No iptables support for family" ipFamily="IPv6"
server.go:654] "kube-proxy running in single-stack mode" ipFamily="IPv4"
...
```

I noticed that the `cilium` package [includes that wrapper script](https://github.com/wolfi-dev/os/blob/0c39ca4357b66feb11c31a3851684f8bfdafbc08/cilium-1.15.yaml#L185-L199), so I tried adding the `cilium-iptables` package, and kube-proxy was able to detect ipv6 support:
```bash
...
server.go:652] "kube-proxy running in dual-stack mode" primary ipFamily="IPv4"
...
```

Would it be possible to add this wrapper script and the `iptables-wrapper` binary as a separate package or a sub-package for the `kube-proxy` package and have it come from the official Kubernetes project [here](https://raw.githubusercontent.com/kubernetes-sigs/iptables-wrappers/v2/iptables-wrapper-installer.sh) instead? Kubernetes includes that in the build process for kube-proxy [here](https://github.com/kubernetes/release/blob/master/images/build/distroless-iptables/distroless-bookworm/Dockerfile#L45-L48).

Thanks in advance!

### Please check all that apply

- [X] This package has an un-restrictive license
- [X] The package/versions proposed are actively maintained upstream
- [X] I am interested in adding this package to Wolfi OS myself
- [X] I am willing to help maintain this package

**Comment by tuananh** [comment]
i think it's better off as separated package because the src code to build is not coming from kube-proxy. they just include it in kube-proxy image.

**Comment by sgalsaleh** [comment]
Makes sense.
