### ISSUE TITLE
[Wolfi Package Request]: php-fpm

### ISSUE THREAD

**Issue by curantes** [wolfi-dev/os#247]
### What software would you like us to add to wolfi-os. Ideally include a URL to the project and its source.

php-fpm: https://www.php.net/
git: https://github.com/php/php-src
source: https://www.php.net/distributions/php-8.0.26.tar.gz 

PHP with fpm enabled
https://www.php.net/manual/en/install.fpm.install.php

### which versions of the software should we include?

8.0.26

### Add some justification for why this specific package and versions are important.

php-fpm is a common way to run the php application so would be nice if it could be added as a sub package to php. Also we are still on 8.0 so would be nice to support all currently supported php versions: 8.2, 8.1, 8.0

This should be nice if there could be a chainguard-images of php-fpm later with the different php versions as well.

### Please check all that apply

- [X] This package has an un-restrictive license
- [ ] I am interested in adding this package to Wolfi OS myself.
- [ ] I am willing to help maintain this package.

**Comment by erikaheidi** [comment]
I can help with adding the 8.1 php-fpm package to Wolfi. In terms of versions, this is something we'll need to discuss with the team to see which versions should be supported, since 8.2 is the latest stable and 8.0 will have only security updates for the next 11 months until it reaches EOL.

**Comment by kaniini** [comment]
This was fixed by #500.
