### ISSUE TITLE
doc: Broken link (https://packages.wolfi.dev/os) at README.md

### ISSUE THREAD

**Issue by Prateeknandle** [wolfi-dev/os#24773]
link : https://packages.wolfi.dev/os, available at [Wolfi description](https://github.com/wolfi-dev/os?tab=readme-ov-file#wolfi) which should provide Wolfi APK package repository is broken.

Solution: 
Need to replace incorrect link with correct one where Wolfi APK package repository is located.

**Comment by tuananh** [comment]
It is the correct link. There just isn't an index.htm(l) file there.
