### ISSUE TITLE
FTBFS: wasi-sdk

### ISSUE THREAD

**Issue by imjasonh** [wolfi-dev/os#24842]
```
2024/07/24 10:36:32 INFO running step "Build"
2024/07/24 10:36:32 WARN make: *** No rule to make target 'build'.  Stop.
```

https://github.com/WebAssembly/wasi-sdk/commit/e29a3fef8b57e9bab2aacccea115cf0c8c9c47f7 rewrote the project's build system, and was included in wasi-sdk 23

I'm not sure how this built when https://github.com/wolfi-dev/os/commit/0cdd37b60c9a0919a028da7e17547438117159fb merged (https://github.com/wolfi-dev/os/pull/23752) -- that postsubmit run is here: https://github.com/wolfi-dev/os/actions/runs/9880154388/job/27288078484

It's also unclear what images rely on wasi-sdk, if any. It might not be worth keeping this around if nothing uses it.

**Comment by debasishbsws** [comment]
https://github.com/wolfi-dev/os/pull/24168 try to build it with these shell instructions, I am able to get it build in the wolfi-base docker container. But it is failing in melange build.

**Comment by debasishbsws** [comment]
we have image zaproxy depend on firefox-esr depends on wasi-sdk-sysroot(subpackage of wasi-sdk)

**Comment by debasishbsws** [comment]
https://github.com/wolfi-dev/os/pull/26527 updated to the new version 24
