### ISSUE TITLE
[Wolfi Package Request]: NMAP

### ISSUE THREAD

**Issue by ahmetak4n** [wolfi-dev/os#2530]
### What software would you like us to add to wolfi-os. Ideally include a URL to the project and its source.

Nmap ("Network Mapper") is a [free and open source](https://nmap.org/npsl/) utility for network discovery and security auditing. Many systems and network administrators also find it useful for tasks such as network inventory, managing service upgrade schedules, and monitoring host or service uptime.

https://nmap.org/

### which versions of the software should we include?

7.94

### Add some justification for why this specific package and versions are important.

It's the latest version of nmap. Nmap is defacto tool in cyber security area.

### Please check all that apply

- [ ] This package has an un-restrictive license
- [X] The package/versions proposed are actively maintained upstream
- [X] I am interested in adding this package to Wolfi OS myself
- [X] I am willing to help maintain this package

also I have prepared a pr #2531

**Comment by ajayk** [comment]
Thanks @ahmetak4n
