### ISSUE TITLE
[Wolfi Package Request]: sftpgo

### ISSUE THREAD

**Issue by tuananh** [wolfi-dev/os#25753]
### What software would you like us to add to wolfi-os. Ideally include a URL to the project and its source.

https://github.com/drakkan/sftpgo

Full-featured and highly configurable SFTP, HTTP/S, FTP/S and WebDAV server - S3, Google Cloud Storage, Azure Blob

license: agpl 3.0

### which versions of the software should we include?

2.6.2

### Please check all that apply

- [X] This package has an un-restrictive license
- [X] The package/versions proposed are actively maintained upstream
- [X] I am interested in adding this package to Wolfi OS myself
- [ ] I am willing to help maintain this package

**Comment by vanlongme** [comment]
plz checkout my draft PR: https://github.com/wolfi-dev/os/pull/25765

**Comment by tuananh** [comment]
Fixed by https://github.com/wolfi-dev/os/pull/25765
