### ISSUE TITLE
unable to install mimalloc2

### ISSUE THREAD

**Issue by Lunarequest** [wolfi-dev/os#2614]
there seems to be a issue with the packaging of mimalloc2 this is the error output `Error: failed to build package: unable to build guest: unable to generate image: installing apk packages: unable to install files for pkg mimalloc2: error creating directory usr/lib64/cmake: mkdir usr/lib64: not a directory` mimalloc2 is a dep on mold and not having mimalloc2 installable makes mold  also impossible to install

**Comment by dlorenc** [comment]
We might need to bump the epoch here, there was a bug in melange awhile back that led to this for some packages

**Comment by ajayk** [comment]
can you please check with the latest version of apko this seems similar to the issue  https://github.com/wolfi-dev/os/pull/1157

**Comment by Lunarequest** [comment]
using the wolfi sdk it works
