### ISSUE TITLE
Packages have symlinks to `/home/build/melange-out/...`

### ISSUE THREAD

**Issue by cipriancraciun** [wolfi-dev/os#26225]
Some packages contain files (especially part of `/bin`, `/usr/bin`, etc.) that are symlinks to files inside `/home/build/melange-out/...`.

Here are a few examples:
* `/bin/ping6` -> `/home/build/melange-out/iputils/bin/ping` (presumably from the package `iputils`);
* `/usr/sbin/tracepath6` -> `/home/build/melange-out/iputils/usr/sbin/tracepath` (the same as above);
* some files installed under `/usr/lib/ccache/bin/*` -> `/home/build/melange-out/ccache/bin/ccache` (part of the `ccache` package);

I haven't investigated to see what other packages might have such symlinks, but given that two unrelated packages (`iputils` and `ccache`) have this, it might imply there is some common underlying issue somewhere in the build framework.

(I am using the latest packages available as of today, 2024-08-13.)

**Comment by tuananh** [comment]
I thought we have built-in linter for dangling symlinks check in melange or wolfictl?
