### ISSUE TITLE
Package Test Failures

### ISSUE THREAD

**Issue by xnox** [wolfi-dev/os#26801]
As in `make test/<package>` failing

From Test World action https://github.com/wolfi-dev/os/actions/runs/10485907649/job/29043674521

- [x] jemalloc: "unable to run pipeline: unable to run pipeline: task exited with code 139"
- [ ] helm-operator: "unable to run pipeline: unable to run pipeline: task exited with code 1"
- [ ] mimalloc2: "unable to run pipeline: unable to run pipeline: task exited with code 139"
- [ ] mimalloc: "unable to run pipeline: unable to run pipeline: task exited with code 139"
- [ ] py3-click: "unable to build guest: unable to generate image: installing apk packages: error getting package dependencies: solving \"py3.10-click\" constraint: could not find package that provides py3.10-click in indexes"
- [ ] py3-cloudpickle: "unable to build guest: unable to generate image: installing apk packages: error getting package dependencies: solving \"py3.10-cloudpickle\" constraint: could not find package that provides py3.10-cloudpickle in indexes"
- [ ] py3-joblib: "unable to build guest: unable to generate image: installing apk packages: error getting package dependencies: solving \"py3.10-joblib\" constraint: could not find package that provides py3.10-joblib in indexes"
- [ ] py3-ipykernel: "unable to run pipeline: unable to run pipeline: unable to run pipeline: task exited with code 1"
- [ ] py3-jupyter-client: "unable to run pipeline: unable to run pipeline: task exited with code 1"
- [ ] py3-pythran: "unable to build guest: unable to generate image: installing apk packages: error getting package dependencies: solving \"py3.10-pythran\" constraint: could not find package that provides py3.10-pythran in indexes"
- [ ] py3-tzdata: "unable to build guest: unable to generate image: installing apk packages: error getting package dependencies: solving \"py3.10-tzdata\" constraint: could not find package that provides py3.10-tzdata in indexes"
- [ ] scudo-malloc: "unable to run pipeline: unable to run pipeline: task exited with code 139"
- [ ] snmalloc: "unable to run pipeline: unable to run pipeline: task exited with code 139"

**Comment by pnasrat** [comment]
These are new packages I think - at least I created `py3-pythran` recently

**Comment by pnasrat** [comment]
```
9cb2eeea4d7f:/work/packages# apk add py3-pythran
fetch https://packages.wolfi.dev/os/x86_64/APKINDEX.tar.gz
(1/22) Installing py3-pip-wheel (24.2-r0)
(2/22) Installing libbz2-1 (1.0.8-r8)
(3/22) Installing libexpat1 (2.6.2-r1)
(4/22) Installing libffi (3.4.6-r4)
(5/22) Installing gdbm (1.24-r0)
(6/22) Installing xz (5.6.2-r0)
(7/22) Installing libgcc (14.2.0-r1)
(8/22) Installing libstdc++ (14.2.0-r1)
(9/22) Installing mpdecimal (4.0.0-r2)
(10/22) Installing ncurses-terminfo-base (6.5_p20240629-r0)
(11/22) Installing ncurses (6.5_p20240629-r0)
(12/22) Installing readline (8.2-r7)
(13/22) Installing sqlite-libs (3.45.1-r1)
(14/22) Installing python-3.12-base (3.12.5-r0)
(15/22) Installing libgfortran (14.2.0-r1)
(16/22) Installing openblas (0.3.28-r0)
(17/22) Installing py3.12-numpy (1.26.4-r4)
(18/22) Installing py3.12-gast (0.6.0-r1)
(19/22) Installing py3.12-beniget (0.4.2-r0)
(20/22) Installing py3.12-ply (3.11_git20180215-r4)
(21/22) Installing python-3.12 (3.12.5-r0)
(22/22) Installing py3-pythran (0.16.1-r0)
OK: 159 MiB in 36 packages
```

**Comment by pnasrat** [comment]
I suspect the py3 packages with `could not find package that provides ` is one cause related to new ish packages with py3 versioned

**Comment by justinvreeland** [comment]
I think these were probably transient failures. They seem to be working fine now. But I don't seem to see that test action in the list of available actions or in the logs to see if it's been run more recently.

**Comment by xnox** [comment]
This is two months old, so likely no longer relevant.
