### ISSUE TITLE
crac support in wolfi java sdk/jre

### ISSUE THREAD

**Issue by tuananh** [wolfi-dev/os#27342]
https://openjdk.org/projects/crac/ 

> The CRaC (Coordinated Restore at Checkpoint) Project researches coordination of Java programs with mechanisms to checkpoint (make an image of, snapshot) a Java instance while it is executing. Restoring from the image could be a solution to some of the problems with the start-up and warm-up times. The primary aim of the [Project](https://openjdk.org/projects/index.html) is to develop a new standard mechanism-agnostic API to notify Java programs about the checkpoint and restore events. Other research activities will include, but will not be limited to, integration with existing checkpoint/restore mechanisms and development of new ones, changes to JVM and JDK to make images smaller and ensure they are correct.

not sure what it takes to get this in wolfi java sdk/jre. looks like these are what we need to do according to this https://github.com/CRaC/openjdk-builds

- build jdk as usual
- build a modified criu https://github.com/CRaC/openjdk-builds
- copy it over to jdk/lib

some other information:

- azul jdk supports it https://www.azul.com/products/components/crac/ . They added support very recently https://github.com/zulu-openjdk/zulu-openjdk/pull/280/files
- this feature will make startup quite a lot faster, especially in serverless workload
- spring already support crac https://docs.spring.io/spring-framework/reference/integration/checkpoint-restore.html

**Comment by tuananh** [comment]
@rawlingsj what do you think? is this something Wolfi team interested it?

**Comment by xnox** [comment]
Unfortunately the mentioned repositories do not provided tagged release matching upstream releases. An alternative source of this feature got packaged however and delivered as an image.

If interested, please see https://images.chainguard.dev/directory/image/jdk-crac/versions and https://images.chainguard.dev/directory/image/jre-crac/versions .
