### ISSUE TITLE
Packages List Truncated at 1000 packages

### ISSUE THREAD

**Issue by johnfosborneiii** [wolfi-dev/os#2735]
https://packages.wolfi.dev/ shows exactly 1,000 packages (1000 instances of <Contents>) whereas there are over 2000 APKs available in the repository. It appears that the 1,000 result limit is originating from an AWS limitation on listing the number of items in a bucket [1] and that some scripting or pagination would need to be set up to work around it

[1] https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjects.html

**Comment by kaniini** [comment]
The listing at packages.wolfi.dev is generated by the GCS bucket itself and isn’t anything we have explicitly deployed.

I am working on an actual package viewer using the new JSON indices though that we could deploy there.
