### ISSUE TITLE
Use `wolfictl lint` in the CI

### ISSUE THREAD

**Issue by Dentrax** [wolfi-dev/os#278]
Recently, we [introduced](https://github.com/wolfi-dev/wolfictl/pull/2) a new `lint` command in the wolfictl as a follow-up for the issue https://github.com/wolfi-dev/os/issues/86. The next step would be using wolfictl in [lint.yaml](https://github.com/wolfi-dev/os/blob/main/.github/workflows/lint.yaml) for CI.

Dropping the idea here so we don't forget! cc @rawlingsj @developer-guy

**Comment by rawlingsj** [comment]
This should be done today.

**Comment by rawlingsj** [comment]
this was merged today https://github.com/wolfi-dev/os/pull/280
