### ISSUE TITLE
xtrans package has bad signature

### ISSUE THREAD

**Issue by tabossert** [wolfi-dev/os#2894]
When trying to install the xtrans package from the Wolfi repository it is returning a bad signature

`(48/73) Installing xtrans (1.5.0-r0)
ERROR: xtrans-1.5.0-r0: BAD signature`

**Comment by imjasonh** [comment]
In case it's helpful to debug this later, [xtrans.zip](https://github.com/wolfi-dev/os/files/11803505/xtrans.zip) contains both x86_64 and aarch64 versions of the offending package.
