### ISSUE TITLE
[Wolfi Package Request]: LibreOffice

### ISSUE THREAD

**Issue by tabossert** [wolfi-dev/os#2896]
### What software would you like us to add to wolfi-os. Ideally include a URL to the project and its source.

LibreOffice

https://www.libreoffice.org/get-help/install-howto/

Source: https://git.libreoffice.org/core

### which versions of the software should we include?

7.5.4

### Add some justification for why this specific package and versions are important.

Libreoffice is an OSS office suite, it is needed to read office documents.  Libreoffice should be installed in headless mode to remove the need for gui packages. 
This is the latest version that has all current security fixes

### Please check all that apply

- [X] This package has an un-restrictive license
- [X] The package/versions proposed are actively maintained upstream
- [X] I am interested in adding this package to Wolfi OS myself
- [X] I am willing to help maintain this package

**Comment by altugbozkurt06** [comment]
any update on this issue ?

**Comment by hughesadam87** [comment]
I'm also itnerestd in this - do you have a sense at least on if this is a all feasible with the current wofli-os?  Following this guide on how to install libreoffice from source: https://wiki.documentfoundation.org/Development/BuildingOnLinux
