### ISSUE TITLE
[Wolfi Package Request]: git-crypt

### ISSUE THREAD

**Issue by gladykov** [wolfi-dev/os#30448]
### What software would you like us to add to wolfi-os. Ideally include a URL to the project and its source.

https://github.com/AGWA/git-crypt

### which versions of the software should we include?

0.7.0

### Add some justification for why this specific package and versions are important.

I encountered Wolfi as a base image for Github Action (1)

Github Actions deal a lot with Git and Git-Crypt is standarized way to keep secrets inside Git repo. There are even Github Actions that process Git-Crypt. (2)

Since afromentioned Github Action based on Wofli cannot include Git-Crypt, part of workflow sometimes fails (3)

git crypt is GPL-3.0

--
(1) https://github.com/planetscale/ghcommit-action
(2) https://github.com/marketplace/actions/github-action-to-unlock-git-crypt-secrets
(3) https://github.com/planetscale/ghcommit-action/issues/75

### Please check all that apply

- [X] This package has an un-restrictive license
- [ ] The package/versions proposed are actively maintained upstream
- [X] I am interested in adding this package to Wolfi OS myself
- [X] I am willing to help maintain this package

**Comment by tuananh** [comment]
@gladykov can you give it a try?

**Comment by gladykov** [comment]
@tuananh Thank you! Once new version of https://github.com/planetscale/ghcommit-action will be released, will report back behavior.
