### ISSUE TITLE
[Wolfi Package Request]: kuberlr

### ISSUE THREAD

**Issue by farcop** [wolfi-dev/os#30607]
### What software would you like us to add to wolfi-os. Ideally include a URL to the project and its source.

https://github.com/flavio/kuberlr

### which versions of the software should we include?

0.5.2

### Add some justification for why this specific package and versions are important.

A tool that simplifies the management of multiple versions of kubectl. 
Allows you to create a universal image to work with all versions of the Kubernetes API

### Please check all that apply

- [x] This package has an un-restrictive license
- [x] The package/versions proposed are actively maintained upstream
- [x] I am interested in adding this package to Wolfi OS myself
- [x] I am willing to help maintain this package

**Comment by farcop** [comment]
Added this package myself https://github.com/wolfi-dev/os/pull/30709

**Comment by ajayk** [comment]
Completed by https://github.com/wolfi-dev/os/pull/30709
