### ISSUE TITLE
[Wolfi Package Request]: Ruby 3.2

### ISSUE THREAD

**Issue by imjasonh** [wolfi-dev/os#307]
### What software would you like us to add to wolfi-os. Ideally include a URL to the project and its source.

https://www.ruby-lang.org/en/news/2022/12/25/ruby-3-2-0-released/

### which versions of the software should we include?

3.2

### Please check all that apply

- [X] This package has an un-restrictive license
- [X] I am interested in adding this package to Wolfi OS myself.
- [X] I am willing to help maintain this package.

**Comment by dlorenc** [comment]
https://github.com/wolfi-dev/os/pull/305 :)

**Comment by kaniini** [comment]
This was fixed by #305.
