### ISSUE TITLE
[Wolfi Package Request]: kakoune

### ISSUE THREAD

**Issue by babariviere** [wolfi-dev/os#30857]
### What software would you like us to add to wolfi-os. Ideally include a URL to the project and its source.

I would like kakoune to be included in wolfi.

Homepage: https://kakoune.org/
Repo: https://github.com/mawww/kakoune

### which versions of the software should we include?

Kakoune 2024.05.18

### Add some justification for why this specific package and versions are important.

It's the editor that I am personally using and would like it to be included in wolfi like vim, neovim and emacs.

### Please check all that apply

- [X] This package has an un-restrictive license
- [X] The package/versions proposed are actively maintained upstream
- [ ] I am interested in adding this package to Wolfi OS myself
- [ ] I am willing to help maintain this package

**Comment by tuananh** [comment]
@babariviere kakoune is now available. can you try it?

**Comment by babariviere** [comment]
@tuananh Works great! Thanks!
