### ISSUE TITLE
Split mariadb into subpackages

### ISSUE THREAD

**Issue by puerco** [wolfi-dev/os#312]
The current mariadb package is quite large (469M/1.2 GB unpacked). There are some very large binaries in it which can potentially be split out into a subpackage. Just these 4 are over 100 MB:

```
132M	local/mysql/bin/mariadb-ldb
132M	local/mysql/bin/sst_dump
216M	local/mysql/bin/mariadbd
219M	local/mysql/bin/mariadb-backup
```

The current apk still packs all manpages and development headers.

**Comment by kaniini** [comment]
It should also be fixed to not use `/usr/local` I guess :)

**Comment by kaniini** [comment]
MariaDB has been fixed up.
