### ISSUE TITLE
[Wolfi Package Request]: php-gd

### ISSUE THREAD

**Issue by letharion** [wolfi-dev/os#3158]
### What software would you like us to add to wolfi-os. Ideally include a URL to the project and its source.

Not strictly a package, but gd support for PHP.
This needs --enable-gd in compilation step.
Details: https://www.php.net/manual/en/image.installation.php

### which versions of the software should we include?

Current PHP version

### Add some justification for why this specific package and versions are important.

Image processing is a common application for PHP.

### Please check all that apply

- [X] This package has an un-restrictive license
- [X] The package/versions proposed are actively maintained upstream
- [X] I am interested in adding this package to Wolfi OS myself
- [ ] I am willing to help maintain this package

**Comment by ajayk** [comment]
recent update php package here in the https://github.com/wolfi-dev/os/pull/3211
