### ISSUE TITLE
[Wolfi Package Request]: NUCLEI

### ISSUE THREAD

**Issue by ahmetak4n** [wolfi-dev/os#3184]
### What software would you like us to add to wolfi-os. Ideally include a URL to the project and its source.

[Nuclei](https://github.com/projectdiscovery/nuclei) is used to send requests across targets based on a template, leading to zero false positives and providing fast scanning on a large number of hosts.

### which versions of the software should we include?

2.9.7

### Add some justification for why this specific package and versions are important.

It's the latest version of the tool. Nuclei provide customized host scan. You can develop and use your custom templates while testing web applications.

### Please check all that apply

- [X] This package has an un-restrictive license
- [X] The package/versions proposed are actively maintained upstream
- [X] I am interested in adding this package to Wolfi OS myself
- [X] I am willing to help maintain this package

Prepared pull request: #3185

**Comment by ajayk** [comment]
Thanks @ahmetak4n , issue was closed in #3185

**Comment by ahmetak4n** [comment]
You are welcome @ajayk 🥳
