### ISSUE TITLE
ruby-3.3: System gems extensions are not build

### ISSUE THREAD

**Issue by Schmitze333** [wolfi-dev/os#33294]
When installing the `ruby-3.3` or `ruby-3.3-dev` package, the native extensions of the system gems seem to not have been built.

This results in warnings like:
```
Source locally installed gems is ignoring #<Bundler::StubSpecification name=debug version=1.9.1 platform=ruby> because it is missing extensions
```

### Minimal steps to reproduce:

```sh
docker run --rm -it cgr.dev/chainguard/wolfi-base

# In the container...
apk update && apk add ruby
gem install bundler
```

### Manual workaround

```sh
apk add build-base
gem pristine --all
apk del build-base
```

**Comment by justinvreeland** [comment]
We fixed this a few months ago and should to be working now. Though we've updated to 3.4
