### ISSUE TITLE
[Wolfi Package Request]: pgbouncer

### ISSUE THREAD

**Issue by jawnsy** [wolfi-dev/os#3413]
### What software would you like us to add to wolfi-os. Ideally include a URL to the project and its source.

The venerable PgBouncer connection pooler

URL: https://www.pgbouncer.org/

Source code: https://github.com/pgbouncer/pgbouncer

License: ISC License

### which versions of the software should we include?

latest (1.9.1)

### Add some justification for why this specific package and versions are important.

Lots of people use PgBouncer for their applications

Bitnami: https://bitnami.com/stack/pgbouncer, https://hub.docker.com/r/bitnami/pgbouncer/

There are various third-party Helm charts floating around as well: https://github.com/cradlepoint/kubernetes-helm-chart-pgbouncer and https://gitlab.cern.ch:8443/pgbouncer/pgbouncer-helm-chart

### Please check all that apply

- [X] This package has an un-restrictive license
- [X] The package/versions proposed are actively maintained upstream
- [ ] I am interested in adding this package to Wolfi OS myself
- [ ] I am willing to help maintain this package

**Comment by ajayk** [comment]
pgbouncer uses pandoc for document generation , which depends on Haskell (ghc or cabal) so its currently blocked by these tooling

**Comment by ajayk** [comment]
@jawnsy : @dlorenc added this in #5300
