### ISSUE TITLE
Move all packages to `./packages/` folder

### ISSUE THREAD

**Issue by Dentrax** [wolfi-dev/os#355]
Currently, the root dir `.` contains more than 300 YAML files; and increasing over time. This would have some pros/cons:
* [+] A cleaner repo
* [+] Make more visible non-packages files (contributing.md, build-scripts, other GitHub specific files, etc.)
* [+] A low-hanging fruit task (edit Makefile and GitHub workflows for new dir)
* [-] I'm not sure, but probably would not be a backward-compatible move?

I was wondering if it would be reasonable for creating a new `./packages/` folder and put the all _packages_ into it. Thoughts?

**Comment by tuananh** [comment]
melange generate the package to `packages` folder by default too. would there be any file conflict if we do that?

**Comment by imjasonh** [comment]
I think this change would be disruptive at this stage, and I don't think it would provide enough value to be worth the pain. Maybe someday when the build system is a bit further along and the number of files is larger it will be worth it.

As @tuananh says, `packages` is already in use during the build, and having it be used for two things could get confusing.
