### ISSUE TITLE
New package(s): docbook-xsl, libxml2-utils, libxslt, docbook-xml

### ISSUE THREAD

**Issue by jdolitsky** [wolfi-dev/os#36]
`docbook-xsl` is required for building manpages for the bubblewrap package

This can be explicitly enabled by setting `-Dman=enabled` on the meson build, but results in:
```
2022/10/18 15:21:23 melange (bubblewrap/x86_64): Program xsltproc found: NO
2022/10/18 15:21:23 melange (bubblewrap/x86_64): 
2022/10/18 15:21:23 melange (bubblewrap/x86_64): meson.build:130:0: ERROR: Program 'xsltproc' not found or not executable
```

Here is the related Alpine APKBUILD: https://git.alpinelinux.org/aports/tree/main/docbook-xsl/APKBUILD

It appears to require also: libxml2-utils, libxslt, docbook-xml (so this may be a rabbit hole)

**Comment by kaniini** [comment]
we will need these things for systemd enablement (*not* going into the core OS, don't worry) later
