### ISSUE TITLE
[Wolfi Package Request]: iotop

### ISSUE THREAD

**Issue by Elizafox** [wolfi-dev/os#3828]
### What software would you like us to add to wolfi-os. Ideally include a URL to the project and its source.

iotop is a command-line I/O monitoring tool

http://guichaz.free.fr/iotop/

### which versions of the software should we include?

0.6

### Add some justification for why this specific package and versions are important.

0.6 is the latest.

iotop is a useful tool for monitoring I/O loads in Linux and is a frequently used tool.

### Please check all that apply

- [X] This package has an un-restrictive license
- [X] The package/versions proposed are actively maintained upstream
- [X] I am interested in adding this package to Wolfi OS myself
- [X] I am willing to help maintain this package

**Comment by Elizafox** [comment]
I've hit a snag... iotop has issues in containers unless the network namespace is shared with the host:

```
[sdk] ❯ ./iotop.py
Netlink error: No such file or directory (2)

The Linux kernel interfaces that iotop relies on for process I/O statistics
were not found. Please enable CONFIG_TASKSTATS in your Linux kernel build
configuration, use iotop outside a container and or share the host's
network namespace with the container.

Please do not file bugs on iotop about this.
```

So I'm wondering if this is worth packaging?

**Comment by dlorenc** [comment]
What are you hoping to use it for? I think we could always document this.

**Comment by Elizafox** [comment]
> What are you hoping to use it for? I think we could always document this.

Trying to see how much I/O a build is performing in a dev container for example.
