### ISSUE TITLE
Package go 1.18

### ISSUE THREAD

**Issue by imjasonh** [wolfi-dev/os#385]
Upstream Go supports the last two releases, which right now are 1.18 and 1.19. We only package 1.19 today.

I think we should follow the example set by go-1.20.yaml (an unreleased rc) and package go-1.18.yaml and go-1.19.yaml, with a `go` package in go.yaml that simply has a runtime dependency on the latest stable go release (currently `go-1.19`).

When go-1.20 is officially released ([expected "Feb 2023"](https://tip.golang.org/doc/go1.20)), go.yaml can update to point to `go-1.20`, go-1.18.yaml can be deleted as it's no longer supported upstream (the `go-1.18` package would continue to exist ~forever), and folks who want 1.19 can still get it by depending on the `go-1.19` package.

We'd follow this same process with go-1.21 has an rc, and later the full release.

Does this sound right @kaniini ?

**Comment by kaniini** [comment]
Yes all of that seems right to me!
