### ISSUE TITLE
[Wolfi Package Request]: gcloud

### ISSUE THREAD

**Issue by jawnsy** [wolfi-dev/os#3887]
### What software would you like us to add to wolfi-os. Ideally include a URL to the project and its source.

Google Cloud SDK

PyPI: https://pypi.org/project/google-cloud/

Unofficial source repositories: https://github.com/google-cloud-sdk-unofficial/google-cloud-sdk

I believe it's Apache 2 licensed

### which versions of the software should we include?

Latest version

### Add some justification for why this specific package and versions are important.

Lots of people use gcloud, and it includes other useful utilities, like a Pub/Sub emulator. Y'all probably use this internally at Chainguard :)

### Please check all that apply

- [X] This package has an un-restrictive license
- [X] The package/versions proposed are actively maintained upstream
- [ ] I am interested in adding this package to Wolfi OS myself
- [ ] I am willing to help maintain this package

**Comment by mattmoor** [comment]
We have `google-cloud-sdk` already :)

**Comment by mattmoor** [comment]
For example, I install it here: https://github.com/mattmoor/wolfstation.

Feel free to reopen if this doesn't address your question.

**Comment by jawnsy** [comment]
Ah, amazing, thanks @mattmoor! I searched for "gcloud" but didn't think to search for "google-cloud-sdk" 🤦

Is there a variant that includes the Pub/Sub emulator? Ideally, I'd love a Chainguard-maintained replacement for https://hub.docker.com/r/thekevjames/gcloud-pubsub-emulator

**Comment by mattmoor** [comment]
Skimming [the Dockerfile](https://github.com/TheKevJames/tools/tree/master/docker-gcloud-pubsub-emulator), we have a lot of the packages, including `pip`, `poetry`, `netcat`, and `wait-for-it`.

We don't have `pubsubc.py` or its `run.sh` packaged, but I wonder if you could achieve almost this entire thing via an image with a complex entrypoint and the listed packages.
