### ISSUE TITLE
Automatically kickoff investigations of potential vulnerabilities

### ISSUE THREAD

**Issue by luhring** [wolfi-dev/os#406]
In order to improve the quality and utility of our advisory data, we should constantly monitor for potential new vulnerabilities in Wolfi packages.

If we detect that a Wolfi package might be affected by a vulnerability, we should have a way to automatically create an advisory, with an entry status of `under_investigation`. This should prompt a Wolfi team member to investigate the potential vulnerability and make a determination on whether we're affected or not. If we are affected, we should patch our package ASAP.

All of this should be as easy as possible for the Wolfi team, while still providing a transparent record to our users of our vulnerability statuses along the way.

#### Implementation considerations:

The existing [secfixes-tracker deployment](https://secfixes-tracker-nd2dq3gc7a-uk.a.run.app/) would be an ideal service to poll, since it's proactively tracking vulnerability matches in NVD on our behalf.

**Comment by dlorenc** [comment]
This is exciting :)

**Comment by luhring** [comment]
The first big chunk of this (i.e. vuln discovery) is done in this PR: https://github.com/wolfi-dev/wolfictl/pull/27

Next step is to agree on a team process for alerting and triaging. I'll work on a document to give a brief overview on what we need and what questions we need to answer as a team.
