### ISSUE TITLE
Add CI check to verify that post-install scripts work correctly

### ISSUE THREAD

**Issue by luhring** [wolfi-dev/os#418]
This might be as simple as creating an ephemeral environment and `apk add`ing the new package? Or perhaps we should also run some assertions to verify an expected state after the scripts exit cleanly.

cc: @rawlingsj

**Comment by kaniini** [comment]
I wonder if this is worth pursuing.  apko doesn’t support scripts by design, for example.

**Comment by pettermk** [comment]
Oh, that sounds like I should not be expecting the above to work at all, then? Not sure what to make out of that, unixodbc drivers need an installation script that tracks usage etc. and the necessary files cannot be added at build time AFAICT. Are there alternatives, like put it in the entrypoint?

Many of the Wolfi packages define trigger scripts, are those also not being run in the chainguard images then?
