### ISSUE TITLE
[Wolfi Package Request]: Just

### ISSUE THREAD

**Issue by mt-inside** [wolfi-dev/os#4511]
### What software would you like us to add to wolfi-os. Ideally include a URL to the project and its source.

Requesting [Just](https://github.com/casey/just), a command-runner and rough Make equivalent.

### which versions of the software should we include?

1.14.0

### Add some justification for why this specific package and versions are important.

I use Just in all my projects to provide useful entrypoints for things like build, test, melange, apko.

I'd like my melange builds to use the same build command that eg GH actions does, so I'm standardising everything to use one Just entrypoint. This means running Just under Melange (yes, I use wolfi as my melange os).

This should be simple: I currently install rust and have melange do `cargo install just` as its first step.
The only issue with this is that Rust builds everything from source, so this is slow, especially in throttled environments like GH actions.

### Please check all that apply

- [X] This package has an un-restrictive license
- [X] The package/versions proposed are actively maintained upstream
- [X] I am interested in adding this package to Wolfi OS myself
- [ ] I am willing to help maintain this package

**Comment by developer-guy** [comment]
thanks for raising an issue @mt-inside 🥳 would you like to give it a try and built just package/image 🤩

**Comment by mt-inside** [comment]
@developer-guy I've been trying, but I can't get any of the packages to build locally, so I can't check it.

I've PR'd anyway: https://github.com/wolfi-dev/os/pull/4512

If you'd be so kind as to review the file, hopefully CI will have better luck building it.

**Comment by mt-inside** [comment]
PR merged, and works in my builds, thanks!
