### ISSUE TITLE
[Wolfi Package Request]: fluent-bit

### ISSUE THREAD

**Issue by patrick-stephens** [wolfi-dev/os#452]
### What software would you like us to add to wolfi-os. Ideally include a URL to the project and its source.

Fluent Bit: https://github.com/fluent/fluent-bit

https://docs.fluentbit.io/

### which versions of the software should we include?

2.0.8+

### Add some justification for why this specific package and versions are important.

Most recent supported version, includes logging, metrics and OTEL output now as well.

### Please check all that apply

- [X] This package has an un-restrictive license
- [X] I am interested in adding this package to Wolfi OS myself.
- [X] I am willing to help maintain this package.

**Comment by patrick-stephens** [comment]
I'm one of the maintainers of fluent bit anyway so happy to help contribute or maintain this

**Comment by tuananh** [comment]
I'm on it :) will check with you if i need help

**Comment by dlorenc** [comment]
This is awesome! We'd love to support fluentbit!

**Comment by patrick-stephens** [comment]
Thanks @tuananh, hopefully it's pretty straightforward. Current builds are containerised in https://github.com/fluent/fluent-bit/tree/master/packaging/distros as an example of dependencies/config you might need. It should all be handled by the top-level CMakeLists.txt though: be aware that some things may silently disable if dependencies to build them are not present (I'm going to raise an improvement on this for a strict mode).

**Comment by tuananh** [comment]
@patrick-stephens kindly help me review the build command in this pr #456 . thank you :)

**Comment by patrick-stephens** [comment]
Thanks @tuananh & @dlorenc, looks good to me to have these. If you want to collaborate (e.g. cross-post on the Fluent blog) or join a [community meeting](https://www.meetup.com/fluent-community-meeting/) to highlight this then please let me or @agup006 know.
