### ISSUE TITLE
question: will we create openjdk package here and use it in chainguard-images/jdk?

### ISSUE THREAD

**Issue by tuananh** [wolfi-dev/os#51]
question: will we create openjdk package here and use it in [chainguard-images/jdk](https://github.com/chainguard-images/jdk)?

**Comment by imjasonh** [comment]
Yep, we plan to. @rawlingsj has been working on getting all the dependencies in place so the JDK can be built. Once the package is built from configs in this repo and available at https://packages.wolfi.dev/os, we'll be able to create an image config at chainguard-images/jdk that builds the JDK package into an image.

**Comment by tuananh** [comment]
that's great to hear. looking fwd to openjdk17 and openjdk17-jre packages :)
