### ISSUE TITLE
Fill in copyright attestations

### ISSUE THREAD

**Issue by imjasonh** [wolfi-dev/os#510]
...or remove them?

We have a bunch of `attestation: TODO`s in our configs.

```
$ git grep "attestation: TODO" | wc -l
     312
```

@kaniini [says](https://github.com/wolfi-dev/os/pull/456/files#r1081928741):

> the attestation should ideally be a collection of the copyright lines plus the "this software is licensed under blabla" text. similar to `debian/copyright`, but we are still kinda playing with the format, so it's not so important right now.

We should figure out what we want these to be and fill them in, or maybe just remove them until we figure out what to do with them. In the meantime they're sort of just cargo-culted around every new config. We don't have any linting in place that it's set or valid, so it's just kind of ...there.

**Comment by kaniini** [comment]
I am working on automated extraction of copyright and license text from built source code.
