### ISSUE TITLE
[Wolfi Package Request]: AMASS

### ISSUE THREAD

**Issue by ahmetak4n** [wolfi-dev/os#5152]
### What software would you like us to add to wolfi-os. Ideally include a URL to the project and its source.

[The OWASP Amass Project](https://github.com/owasp-amass/amass) performs network mapping of attack surfaces and external asset discovery using open source information gathering and active reconnaissance techniques. 

### which versions of the software should we include?

4.1.0

### Add some justification for why this specific package and versions are important.

AMASS is very popular tool for OSINT. 

### Please check all that apply

- [X] This package has an un-restrictive license
- [X] The package/versions proposed are actively maintained upstream
- [X] I am interested in adding this package to Wolfi OS myself
- [X] I am willing to help maintain this package

**Comment by kaniini** [comment]
Merged in #5153
