### ISSUE TITLE
[Wolfi Package Request]: lobgeos

### ISSUE THREAD

**Issue by PickledDragon** [wolfi-dev/os#5422]
### What software would you like us to add to wolfi-os. Ideally include a URL to the project and its source.

I would like to have the shared library `libgeos` to be included as a part of Wolfi.
I was trying to migrate my usage of `python:slim` image to Chainguard images because of its light weight and miniscule attack surface. However my use case depends on `libgeos` and it is not present in Wofi stack but is is available on Alpine.

Source URL for `libgeos`: https://libgeos.org/

### which versions of the software should we include?

3.12.0-r0

### Add some justification for why this specific package and versions are important.

Several usecases in the GIS space and increasingly in generative AI space dependes on libgeos. A list(not comprehensive) - is here: https://libgeos.org/usage/bindings/
I currently lack the skills to try this out or send an upstream commit, though I would love to do that.

### Please check all that apply

- [X] This package has an un-restrictive license
- [X] The package/versions proposed are actively maintained upstream
- [ ] I am interested in adding this package to Wolfi OS myself
- [ ] I am willing to help maintain this package

**Comment by rawlingsj** [comment]
Hi @PickledDragon sounds good!  I just pushed a PR, hopefully it will be reviewed, merged and available in Wolfi sometime today.
