### ISSUE TITLE
Request: make `https://packages.wolfi.dev/os` browsable from web browsers

### ISSUE THREAD

**Issue by AkihiroSuda** [wolfi-dev/os#5439]
Currently https://packages.wolfi.dev/os is not browsable:
```
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
</Error>
```

**Comment by tuananh** [comment]
this can be done in `melange index`? together with the apkindex, we can make it optinal to generate a simple html file for browsing?

**Comment by tstromberg** [comment]
I came to add the same issue - there should be a way to browse and download APKs from a web browser. I had expected the https://packages.wolfi.dev/os link from the front page to work for browsing, but it does not.

The URL does however work for downloading APKs but you have to know the name and version first. For example: https://packages.wolfi.dev/os/aarch64/kaniko-1.13.0-r1.apk
