### ISSUE TITLE
[Wolfi Package Request]: argocd

### ISSUE THREAD

**Issue by kameshsampath** [wolfi-dev/os#544]
### What software would you like us to add to wolfi-os. Ideally include a URL to the project and its source.

As GitOps user I would like to install [argocd](https://github.com/argoproj/argo-cd) CLI. 

### which versions of the software should we include?

v2.6.0

### Add some justification for why this specific package and versions are important.

Argo CD CLI is one of the popularly used GitOps platform and this CD helps interacting Argo CD clusters.

### Please check all that apply

- [X] This package has an un-restrictive license
- [X] I am interested in adding this package to Wolfi OS myself.
- [X] I am willing to help maintain this package.

**Comment by patflynn** [comment]
perhaps relevant issue in argoproj https://github.com/argoproj/argo-cd/issues/9029#issuecomment-1429888734
