### ISSUE TITLE
Request: support armv7, s390x, ppc64le, riscv64

### ISSUE THREAD

**Issue by AkihiroSuda** [wolfi-dev/os#5440]
Currently, wolfi seems to support only amd64 and arch64.

However, typical multi-platform images support armv7, s390x, ppc64le, and riscv64 (although they are rarely used).

Supporting these additional platform may help adopting wolfi.

**Comment by kaniini** [comment]
At present, our plan is to stick with amd64 and aarch64, as they represent the vast majority of systems in the world today.  We may add riscv64 in the future, assuming that we can solve the bootstrapping problems and also set up reliable build infrastructure that can keep up with builds.

We are unlikely to produce 32-bit builds, e.g. i386/armv7, given the trend of some widely-used modern software requiring more than 4GB of RAM to compile.

With regards to the IBM architectures (s390x and ppc64le), without customer demand, Chainguard itself is unlikely to pursue supporting these.  We would probably be okay with other stakeholders maintaining support for these architectures, however.

**Comment by AkihiroSuda** [comment]
Thank you for clarifying

**Comment by endersonmaia** [comment]
What if I can spin up some infra to build for riscv64, how could we collaborate to host this upstream?

I'm trying to boostrap a repository for riscv64 and reporting at a [#apko channel thread](https://kubernetes.slack.com/archives/C03MASRQP4M/p1712850815118019) on Kubernetes' Slack.

**Comment by endersonmaia** [comment]
I'm trying to bootstrap wolfi-os to riscv64 at https://github.com/endersonmaia/wolfi-os-riscv64-bootstrap, any help is appreciated.
