### ISSUE TITLE
[Wolfi Package Request]: Eclipse Adoptium Temurin JDK and JRE

### ISSUE THREAD

**Issue by ryandens** [wolfi-dev/os#5509]
### What software would you like us to add to wolfi-os. Ideally include a URL to the project and its source.

👋 Hi, really excited to see all the development and amazing work that's been put in here! I'm interested in using apko to build the base image for my application. One of the application's requirement is a Java runtime. The work being put into the provenance of the wolfi JDK and JRE is nothing short of incredible, I really appreciated [the blog post](https://www.chainguard.dev/unchained/fully-bootstrapping-java-from-source-in-wolfi) and can understand why this is an important issue to solve for many people.

While I am excited about the prospect of a fully open-source JDK distribution like Wolfi, my greater concern is the lack of testing on the distribution itself. Namely, I feel nervous about adopting a JDK distribution that has not passed the TCK ([yet](https://www.chainguard.dev/unchained/fully-bootstrapping-java-from-source-in-wolfi)) or a similar test suite.

In the short term, would you consider packaging Temurin binaries in Wolfi OS? I would be happy to contribute to help this happen. 

### which versions of the software should we include?

17, 20

### Add some justification for why this specific package and versions are important.

17 is the latest LTS version, 20 is the latest version. JDK 21 is coming very soon, so we might also start the work on that. We should also consider adding 11 as another LTS version, but I don't know how valuable that would be. 

### Please check all that apply

- [X] This package has an un-restrictive license
- [X] The package/versions proposed are actively maintained upstream
- [X] I am interested in adding this package to Wolfi OS myself
- [X] I am willing to help maintain this package

**Comment by kaniini** [comment]
Wolfi does not package pre-compiled binaries as a matter of policy.

**Comment by ryandens** [comment]
👍 Ah, understood, I misunderstood the posture here. Is the best path forward for a TCK-compliant Java runtime in a wolfi-based image to package up an APK from the precompiled binary with Melange?
