### ISSUE TITLE
Refactor APKINDEX generation

### ISSUE THREAD

**Issue by imjasonh** [wolfi-dev/os#551]
Today we generate the APKINDEX like so:

1. GitHub CI builds and publishes new apks to the `source` bucket
1. A Cloud Function watches for new files in the `source` bucket, which when triggered:
    1. generates an APKINDEX from all the apks in the `destination` bucket, plus the new file in the `source` bucket that triggered the function
    1. writes the new apk and the updated APKINDEX to the `destination` bucket where users consume it
    1. deletes the new apk from the `source` bucket

The result is that the `destination` bucket contains all the apks we build, plus an APKINDEX containing all the apks in the bucket.

This has some problems:

1. When we publish many apks at once, the function triggers for each new apk, regenerating a new APKINDEX repeatedly and repeatedly pulling apks from the bucket to do so. Either the function has to run sequentially for each new apk, or it has to fail and retry when the APKINDEX it's replacing is different from the one it expected (effectively running the process in sequence, with more wasteage)
1. The `source`->`destination` dance is not actually needed, since it's perfectly fine for the `destination` bucket to contain apks that aren't expressed in the APKINDEX
1. Having a Cloud Function means maintaining more infrastructure, which is currently private and not transparent to the community
1. To purge a package from the index today we delete the offending apk in the bucket, which triggers an APKINDEX rebuild, a process which is also not transparent to the community. Purging packages is a destructive action, how and when it happens should be more visible to package consumers.
1. To rebuild the APKINDEX on-demand (as sometimes we need to do, if there's a bug in APKINDEX generation for example) we delete the APKINDEX in the bucket, which triggers the Cloud Function. This leads to downtime while the APKINDEX is unavailable, which is exacerbated by...
1. generating the APKINDEX takes longer and longer the more packages we have (https://github.com/chainguard-dev/melange/issues/279), and we're starting to get enough packages that it's becoming painful.

---

I think we can simplify the above to make it require less infrastructure, make what infrastructure it requires more transparent and auditable, and save time and reduce waste.

1. Add a method to `wolfictl` to generate an APKINDEX from the list of apks in a GCS bucket, and sign and publish that APKINDEX back to the bucket
1. Run this `wolfictl` command after each build completes and new packages are published. This will add N new packages to the APKINDEX at once, instead of running N times to add one package each.
1. Run this `wolfictl` command in GitHub Actions hourly, and on-demand. When the command runs its logs will be publicly visible.

This will let us turndown the `source` bucket and Cloud Function, and the code that generates the APKINDEX will be public and when it runs its logs will be public. When an APKINDEX is refreshed, it will be replaced in-place, rather than deleted and regenerated.

There are also some optimizations we can make when consuming apks to generate the APKIDNEX, so that index generation doesn't take as long.

**Comment by imjasonh** [comment]
Here's a slight wrinkle. Not a problem, just a thing I realized while trying to roll this out starting with stage1. The APKINDEX-generating Cloud Function will trigger on new apks in any repo using the bucket, and generate an APKINDEX for those repos, potentially racing with / stomping on output from a GitHub Actions-triggered APKINDEX generator.

"Rolling out" is roughly:
- update CI to publish directly to the `destination` bucket (e.g., [here](https://github.com/wolfi-dev/os/actions/runs/4126129458/workflow#L75) and [here](https://github.com/wolfi-dev/os/actions/runs/4126129438/workflow#L15))
- add a step after the build completes to run `wolfictl generate-index --repo=<repo> --publish --signing-key=./wolfi-signing.rsa`
- add a workflow that runs on a cron+manually to run `wolfictl` as above.

We can roll this out starting with stage1, but it might get stomped by the Function before we can practically verify it. Luckily we can just re-run the workflow to generate it again. Then we roll it out through stage2-3 and os, and turn down the Cloud Function.

**Comment by tuananh** [comment]
@imjasonh can we use a database? eg like dynamodb on aws. not sure what's the equivalent on gcp.

- having a cloudrun function to watch the bucket event on put/delete => generate a record in the database. this is suppose to be fast.
- generate the index from database. this is suppose to be very quick too.

downside:
- having additional database to maintain.

**Comment by kaniini** [comment]
No need to use a database, I would prefer to keep things stateless.

**Comment by tuananh** [comment]
> No need to use a database, I would prefer to keep things stateless.

how about having somewhhere (another bucket) to keep metadata of the parsed package as cache? lookup metadata via hash of the build apk file so that we don't have to parse the apk every single time?

most of the time is spent in apkrepo.parsePackage at the moment i think.

**Comment by imjasonh** [comment]
I think it could be useful to write `APKINDEX.tar.gz` and the equivalent `index.json` or something to the bucket, so that folks who want to consume the package list as JSON don't have to fetch and parse repeatedly. I don't know if Alpine has a similar thing that we should try to standardize on.

A `<package>.json` for each package might not be worth it, versus just fetching the index.json and finding the package metadata you want:

```
$ wolfictl index | jq '.Packages[] | select(.Name == "busybox") | select(.Version == "1.36.0-r0")'
{
  "Name": "busybox",
  "Version": "1.36.0-r0",
  "Arch": "x86_64",
...
```
