### ISSUE TITLE
image-magick:7.1.1-18

### ISSUE THREAD

**Issue by ahmetak4n** [wolfi-dev/os#6063]
### What software would you like us to add to wolfi-os. Ideally include a URL to the project and its source.

[ImageMagick®](https://imagemagick.org/) is a free and [open-source](https://imagemagick.org/script/license.php) software suite for displaying, converting, and editing raster image and vector image files. It can read and write over 200 image file [formats](https://imagemagick.org/script/formats.php), and can support a wide range of image manipulation operations, such as resizing, cropping, and color correction.

### which versions of the software should we include?

7.1.1-18

### Add some justification for why this specific package and versions are important.

ImageMagick is so popular image editing libraries. Dev teams requires this libraries while resize, edit or converting images in run-time. 7.1.1-18 is latest version of image magick

### Please check all that apply

- [X] This package has an un-restrictive license
- [X] The package/versions proposed are actively maintained upstream
- [X] I am interested in adding this package to Wolfi OS myself
- [X] I am willing to help maintain this package

Also I prepared a pull request for the package. #6064

**Comment by ajayk** [comment]
This was addressed by #7697
