### ISSUE TITLE
Create `netshoot` image

### ISSUE THREAD

**Issue by Dentrax** [wolfi-dev/os#619]
[Netshoot](https://github.com/nicolaka/netshoot) (~6k stars) is one of the widely known network troubleshooting image and using across cloud native era.

It contains the following packages: https://github.com/nicolaka/netshoot/blob/d61507f29a1ea2cd27acf6facde09f8e50ba7372/Dockerfile#L12-L72

My proposal is to recreate the same image in Wolfi to achieve 0-CVE.

Wdyt?

/cc @nicolaka @developer-guy

**Comment by tuananh** [comment]
that's lots of pkg :D 

let's do one by one :) i'll go first. https://github.com/wolfi-dev/os/pull/627

**Comment by nicolaka** [comment]
I will look into this and see how feasible is it to create a wolfe base image.

**Comment by tuananh** [comment]
@Dentrax @nicolaka I'm doing it over here if anyone want to collaborate https://github.com/tuananh/netshoot

**Comment by tuananh** [comment]
there are a bunch of new packages. i will be adding them back to wolfi once we complete everything
