### ISSUE TITLE
Setting the timezone in wolfios

### ISSUE THREAD

**Issue by dwaynebradley** [wolfi-dev/os#65]
Is there a way to set the timezone in wolfios? I currently have not been able to figure out how to change it.

**Comment by kaniini** [comment]
We will need to package tzdata, but at that point it works like any other distro, symlink or copy the relevant zoneinfo file to /etc/timezone

**Comment by dwaynebradley** [comment]
Yeah, I didn't see `tzdata` when I ran `apk list --all` earlier. I only saw `tzutils` available.

**Comment by kaniini** [comment]
Yes, will take care of it in the morning

**Comment by dwaynebradley** [comment]
Oh, that's awesome! :-) Thanks @kaniini

**Comment by dwaynebradley** [comment]
Thanks @kaniini 😎
