### ISSUE TITLE
checkov package is not usable

### ISSUE THREAD

**Issue by tuananh** [wolfi-dev/os#6715]
What I did

```sh
docker run -it --rm cgr.dev/chainguard/wolfi-base
apk add checkov
checkov
```

I got the following error

```bash
cd08f75ce732:/# checkov
Traceback (most recent call last):
  File "/usr/bin/checkov", line 2, in <module>
    from checkov.main import Checkov
ModuleNotFoundError: No module named 'checkov'
```

Tagging @ahmetak4n

**Comment by ahmetak4n** [comment]
Hi @tuananh I will check it 🙏

**Comment by rawlingsj** [comment]
This might be related to a python 3.12 update that's happening.  Sorry about this, investigating also.

**Comment by vaikas** [comment]
I got confused it was complaining during the install, my bad. Looking into it.

**Comment by ahmetak4n** [comment]
<img width="1718" alt="image" src="https://github.com/wolfi-dev/os/assets/30419196/13aeffe8-102b-46df-bc75-40cd59ce9a09">
It worked with python 3.12. I need to find a clean way for adding that the required dependencies. fyi

**Comment by ahmetak4n** [comment]
Could I suggest remove checkov until release a stable version of checkov3 https://github.com/bridgecrewio/checkov3 @tuananh.?

**Comment by tuananh** [comment]
not a problem for me. can't say for others.

**Comment by ahmetak4n** [comment]
Checkov3 different repository and it has not contain any release https://github.com/bridgecrewio/checkov3 🙏

**Comment by tuananh** [comment]
@ahmetak4n  looks like he forked from checkov repo and worked on it for awhile.

but now it's merged back to main repo already

![image](https://github.com/wolfi-dev/os/assets/627278/b9c24f32-4446-4d61-b95c-232f8d7b09f7)

**Comment by ahmetak4n** [comment]
I committed a fix for checkov. #8081
