### ISSUE TITLE
Fix llhttp/9.1.3 package update (#6945)

### ISSUE THREAD

**Issue by erikaheidi** [wolfi-dev/os#7018]
The auto-update PR for `llhttp/9.1.3` is broken. Check PR #6945 for more details.

_Don't forget to leave a comment if you want to claim this issue for Hacktoberfest._

**Comment by debasishbsws** [comment]
Hey @erikaheidi, I have a doubt here, I am trying to build the current llhttp package locally but when I run
```bash
docker run --privileged -v "$PWD":/work --entrypoint=melange --workdir=/work ghcr.io/wolfi-dev/sdk build \
--keyring-append local-melange.rsa.pub --keyring-append https://packages.wolfi.dev/os/wolfi-signing.rsa.pub \
--signing-key local-melange.rsa --repository-append https://packages.wolfi.dev/os  --repository-append /work/packages \
--empty-workspace --arch arm64 llhttp.yaml
```
I am getting error in the `patch` saying `⚠️  aarch64   | /bin/sh: can't open fix-sed.patch: no such file`

I am not sure what to do here. Can you suggest me what should I do to build package locally when there is a patch section?

**Comment by dlorenc** [comment]
Instead of --empty-workspace try passing --source-dir=llhttp
