### ISSUE TITLE
nspr duplicated?

### ISSUE THREAD

**Issue by lpcalisi** [wolfi-dev/os#7311]
Recently two `nspr` PRs was merged. Both depends on the same release monitor ID.

https://github.com/wolfi-dev/os/pull/7203
https://github.com/wolfi-dev/os/pull/7291

**Comment by mattmoor** [comment]
You are right!  I checked the repo, but didn't realize this was in-flight.

I need `nss` too which I see is also in flight (I was going to start on this today).

I have no real preference over which version of this we keep, but I left a handful of review comments on @mesaglio PR noting some differences / problems we should fix up if we revert/withdraw `nspr.yaml`.

If the comments make sense, I can sent a PR that reverts mine, withdraws `nspr` and fixes up the comments on #7203?  WDYT?

**Comment by mattmoor** [comment]
Also wanted to say thanks for catching this AMAGINGLY quickly 🤯

**Comment by lpcalisi** [comment]
Thanks! We are working on with @mesaglio  support [cypress](https://github.com/cypress-io/cypress) and we contribute with all the [needed packages](https://docs.cypress.io/guides/getting-started/installing-cypress#UbuntuDebian) missed in Wolfi

**Comment by mattmoor** [comment]
Sent a PR with the changes mentioned!

**Comment by mesaglio** [comment]
Hi, @mattmoor.

Thanks for your feedback! I'll keep that in mind with libnss pr #7205.
Today we pass this to review

**Comment by mattmoor** [comment]
@mesaglio yeah thanks for that as well.  I will grab that and try it out this afternoon!
