### ISSUE TITLE
Elastic Licence

### ISSUE THREAD

**Issue by lpcalisi** [wolfi-dev/os#7454]
We closes https://github.com/wolfi-dev/os/pull/7407 because we understand that Elastic License have some limitations and should not be provided on Wolfi but provides [logstash](https://github.com/wolfi-dev/os/blob/main/logstash.yaml) that have the same license.

What should we do? I believe that Elastic License apply only in the `x-pack` folder.

**Comment by kaniini** [comment]
AFAIK we only package the OSS components, not the x-pack ones.
