### ISSUE TITLE
`clang-16` does not add `libclang-cpp-16` library result in faliure

### ISSUE THREAD

**Issue by debasishbsws** [wolfi-dev/os#7529]
in Wolfi when we install `clang-16` libclang-cpp-* doesn't get added. It is not the case with other versions like `clang-15`.

It causes command failures:
![image](https://github.com/wolfi-dev/os/assets/65381620/f48eb8b1-ccb2-425f-b5f5-0e5d3d7e98ac)

**Comment by tuananh** [comment]
@rawlingsj looks like sth broke recently. `clang-16==16.0.6-r0` works while `r1` doesn't.

This is the result of `apk dot clang-16 | grep libclang`
```sh
...
  "libclang-cpp-16-16.0.6-r1" -> "libstdc++-13.1.0-r1"[arrowhead=inv,label="so:libstdc++.so.6",];
  "libclang-cpp-16-16.0.6-r1" -> "libstdc++-13.2.0-r0"[arrowhead=inv,label="so:libstdc++.so.6",];
  "libclang-cpp-16-16.0.6-r1" -> "libstdc++-13.2.0-r1"[arrowhead=inv,label="so:libstdc++.so.6",];
  "libclang-cpp-16-16.0.6-r1" -> "libstdc++-13.2.0-r2"[arrowhead=inv,label="so:libstdc++.so.6",];
  "libclang-cpp-16-16.0.6-r1" -> "libstdc++-13.2.0-r3"[arrowhead=inv,label="so:libstdc++.so.6",];
  "clang-16-16.0.6-r0" -> "libclang-cpp-16-16.0.6-r1"[arrowhead=inv,label="so:libclang-cpp.so.16",];
```

Looks like an entry for `clang-16-16.0.6-r1` is misisng.
