### ISSUE TITLE
Support multiple python 3.x streams

### ISSUE THREAD

**Issue by westonsteimel** [wolfi-dev/os#78]
It would be incredibly useful to have some way of having packages for each currently supported python 3 stream, so currently I think

- 3.11
- 3.10
- 3.9
- 3.8
- 3.7 (though I think this just has 7 months or so left)

I saw https://github.com/wolfi-dev/os/pull/75 and wondered if a similar approach is possible; however, python seems a bit more complicated since there are also a bunch of py3-* packages that'd probably have to be split out as well since they currently have runtime dependencies on `python3`

**Comment by kaniini** [comment]
It can be done, we just need to clarify that the `py3-` packages are for the system python implementation only, and then mark that stream with a virtual like `system-python`.

**Comment by kaniini** [comment]
Multiple python streams are now supported.
