### ISSUE TITLE
[Wolfi Package Request]: checkov

### ISSUE THREAD

**Issue by ahmetak4n** [wolfi-dev/os#796]
### What software would you like us to add to wolfi-os. Ideally include a URL to the project and its source.

I want to add checkov tool in wolfi-os. It is a IaC scanning tool. We are going to plan this tools scan our terraform, etc. repositories
**Tool Gitlab:** https://github.com/bridgecrewio/checkov
**Tool Python Wheel:** https://files.pythonhosted.org/packages/ea/2b/2b0826f1f0e8c20837658c7648b94e43a21109f6be8d764cad301465fae1/checkov-2.3.105-py3-none-any.whl

### which versions of the software should we include?

2.3.96

### Add some justification for why this specific package and versions are important.

Actually I prepared a melange file for checkov tool and import it to our custom image via apko. I just want to share my experience with you. Also I think different people want to use this package. 

### Please check all that apply

- [X] This package has an un-restrictive license
- [X] The package/versions proposed are actively maintained upstream
- [X] I am interested in adding this package to Wolfi OS myself
- [ ] I am willing to help maintain this package

**Comment by imjasonh** [comment]
Sounds good!

FWIW, it looks like the latest released version is [`2.3.102`](https://github.com/bridgecrewio/checkov/releases/tag/2.3.102), released 20 hours ago.

**Comment by ahmetak4n** [comment]
Thanks @imjasonh, I will try it 🥳

**Comment by tuananh** [comment]
@imjasonh do we allow direct fetching `whl` file or it must be built from source?

`whl` file is binary right?

**Comment by kaniini** [comment]
Everything in Wolfi needs to be built from source.
