### ISSUE TITLE
[Wolfi Package Request]: semgrep

### ISSUE THREAD

**Issue by ahmetak4n** [wolfi-dev/os#797]
### What software would you like us to add to wolfi-os. Ideally include a URL to the project and its source.

Semgrep is popular source code analysis tool. We want to use this tool in our custom images. That's why we want to import it to wolfi-os.

**Project Github:** https://github.com/returntocorp/semgrep

**Project Python Wheel:** https://files.pythonhosted.org/packages/9d/e7/5a31be69c8dc355aee831e0a282bbc39ec3f31ebfcd5d5a7b3fab514e13e/semgrep-1.15.0-cp37.cp38.cp39.py37.py38.py39-none-any.whl

### which versions of the software should we include?

1.15.0

### Add some justification for why this specific package and versions are important.

Semgrep is most popular source code analysis tool. We are going to prepare a image that contains security tool like SAST, SCA, etc. We will use this image for scan our project in Gitlab or Github runners. If wolfi-os include this tool, a lot of person can use these package for same purpose. Also I prepared a melage file for semgrep and push it our custom images with apko in our local system.

### Please check all that apply

- [ ] This package has an un-restrictive license
- [X] The package/versions proposed are actively maintained upstream
- [X] I am interested in adding this package to Wolfi OS myself
- [ ] I am willing to help maintain this package

**Comment by patflynn** [comment]
[Licensing](https://github.com/returntocorp/semgrep/blob/develop/LICENSE) looks [fine](https://spdx.org/licenses/) (OSI approved).

**Comment by dlorenc** [comment]
+1 to shipping this!

**Comment by goproslowyo** [comment]
I gave this an attempted first-pass https://github.com/wolfi-dev/os/pull/4262

**Comment by ahmetak4n** [comment]
Hi @goproslowyo,

I'm facing with  this error while trying semgrep`Failed to find semgrep-core in PATH or in the semgrep package.` Do you have any idea about it?

I added semgrep package in my apko file like `py3-semgrep`
![image](https://github.com/wolfi-dev/os/assets/30419196/428ee9fc-42bd-40ca-a3fa-3d806c422b0e)

**Comment by goproslowyo** [comment]
Hey @ahmetak4n py3-semgrep is just a python wrapper that calls out to semgrep-core. semgrep-core is an ocaml binary, so you'll need the `semgrep ` package itself which contains the `semgrep-core` binary.

**Comment by goproslowyo** [comment]
@ahmetak4n There was a problem with semgrep-core and py3-semgrep where the versions got out of sync because I committed the wrong GH repo name to the auto-update. Should be fixed now so try it out!

**Comment by ahmetak4n** [comment]
Hi @goproslowyo thanks for the response. It seems solved.
