### ISSUE TITLE
Melange v0.51 vendored dependencies broke some builds

### ISSUE THREAD

**Issue by lpcalisi** [wolfi-dev/os#8209]
Release [v0.51](https://github.com/chainguard-dev/melange/compare/v0.5.0...v0.5.1#diff-4da650abab6a3c2096da754c5d2ad8e0b7c1548be5a03d8422f188bc13287983R553-R708) introduces Vendored dependencies, it improves use prefix `/usr/` but some packages are compiled without this flag, so those packages are corrupted.

For example:

````console
[sdk] ❯ apk add libxkbcommon
WARNING: opening ./../../packages: No such file or directory
ERROR: unable to select packages:
  libxkbcommon-1.5.0-r0:
    conflicts: libxkbcommon-1.6.0-r0
    satisfies: world[libxkbcommon] libxkbcommon-1.6.0-r0[so:libxkbcommon-x11.so.0]
               libxkbcommon-1.6.0-r0[so:libxkbcommon.so.0]
               libxkbcommon-1.6.0-r0[so:libxkbregistry.so.0]
  libxkbcommon-1.6.0-r0:
    conflicts: libxkbcommon-1.5.0-r0
    satisfies: world[libxkbcommon]
````

As you can see, version 1.6.0 depends on `libxkbcommon-x11.so.0` that was provided by the oldest versions of `libxkbcommon`

```console
libxkbcommon-1.6.0-r0 depends on:
so:ld-linux-aarch64.so.1
so:libc.so.6
so:libwayland-client.so.0
so:libxcb-xkb.so.1
so:libxcb.so.1
so:libxkbcommon-x11.so.0
so:libxkbcommon.so.0
so:libxkbregistry.so.0
so:libxml2.so.2

libxkbcommon-1.6.0-r0 provides:
pc:xkbcommon-x11=1.6.0
pc:xkbcommon=1.6.0
pc:xkbregistry=1.6.0
````

````console
libxkbcommon-1.5.0-r0 depends on:
so:ld-linux-aarch64.so.1
so:libc.so.6
so:libwayland-client.so.0
so:libxcb-xkb.so.1
so:libxcb.so.1
so:libxml2.so.2

libxkbcommon-1.5.0-r0 provides:
so:libxkbcommon-x11.so.0=0
so:libxkbcommon.so.0=0
so:libxkbregistry.so.0=0
````

@kaniini  @mattmoor @imjasonh @jonjohnsonjr 

cc @mesaglio

**Comment by lpcalisi** [comment]
`libcap` is also broken with this merged version but the prefixes are fine, the problem here is that libcap provides `libpsx.so.2` and it has an interpreter like libc and it doesn't enter the [condition](https://github.com/chainguard-dev/melange/blob/main/pkg/sca/sca.go#L321) in melange sca

**Comment by jonjohnsonjr** [comment]
Related: https://github.com/wolfi-dev/os/issues/6199

**Comment by lpcalisi** [comment]
@jonjohnsonjr @imjasonh do you think about libcap? It is broken
