### ISSUE TITLE
[Question] any plans to add build-essential or alpine-sdk to Wolfi packages repos?

### ISSUE THREAD

**Issue by pollosp** [wolfi-dev/os#843]
Hi, I'm packaging with melange a Ruby + Puma + Sinatra app which has some C dependencies and it is being a bit painful. 

I want to build the app package fully with Wolfi sources to keep build as much consistent as I can. 

Problem I find is with available Wolfi packages , I don't find meta packages like Debian build-essential or alpine-sdk for my environment into the build stage. 

As I wrote I could switch to alpine sources but I would stick to yours for consistency as I new with Melange I don't know if this is the good pattern but using Wolfi looks like the way to go to me.

Here is my test (still WIP) as I don't have all the dependencies I need 

https://gist.github.com/pollosp/b5dac762aa0da7f8c109097e9400ab08

Thanks in advance

**Comment by kaniini** [comment]
The equivalent to `build-essential` in Wolfi is `build-base`.
