### ISSUE TITLE
[Wolfi Package Request]: glab (gitlab-cli)

### ISSUE THREAD

**Issue by MindTooth** [wolfi-dev/os#8539]
### What software would you like us to add to wolfi-os. Ideally include a URL to the project and its source.

Seeing that today you already have several GitLab images, I tried to find one for `glab`, but could not find one.

https://gitlab.com/gitlab-org/cli

Can of course start with the recent and keep it up to date later down the road.

### which versions of the software should we include?

1.35

### Add some justification for why this specific package and versions are important.

I think [`glab`](https://gitlab.com/gitlab-org/cli) is a really nice tool for interactiv with GitLab.  My current use case it just to work against its own API via a pipeline using a `$CI_JOB_TOKEN`.  Instead of having a large image and doing some stuff myself.  I would rather use chainguard which just contains `glab` that can e.g. do something like `glab api --method=DELETE projects/:id/packages/1337`

### Please check all that apply

- [X] This package has an un-restrictive license
- [X] The package/versions proposed are actively maintained upstream
- [X] I am interested in adding this package to Wolfi OS myself
- [X] I am willing to help maintain this package

**Comment by ajayk** [comment]
@MindTooth glad cli is already available under wolf here https://github.com/wolfi-dev/os/blob/main/glab.yaml

```
/ # apk update
fetch https://packages.wolfi.dev/os/aarch64/APKINDEX.tar.gz
 [https://packages.wolfi.dev/os]
OK: 27288 distinct packages available
/ # apk add glab
(1/1) Installing glab (1.35.0-r1)
OK: 38 MiB in 15 packages
/ # glab --version
glab version 1.35.0
/ # glab --help
GLab is an open source GitLab CLI tool that brings GitLab to your command line.

USAGE
  glab <command> <subcommand> [flags]

CORE COMMANDS
  alias:       Create, list and delete aliases
  api:         Make an authenticated request to GitLab API
  ask:         Generate terminal commands from natural language. (Experimental.)
  auth:        Manage glab's authentication state
  changelog:   Interact with the changelog API
  check-update: Check for latest glab releases
  ci:          Work with GitLab CI/CD pipelines and jobs
  cluster:     Manage GitLab Agents for Kubernetes and their clusters
  completion:  Generate shell completion scripts
  config:      Set and get glab settings
  help:        Help about any command
  incident:    Work with GitLab incidents
  issue:       Work with GitLab issues
  label:       Manage labels on remote
  mr:          Create, view and manage merge requests
  release:     Manage GitLab releases
  repo:        Work with GitLab repositories and projects
  schedule:    Work with GitLab CI schedules
  snippet:     Create, view and manage snippets
  ssh-key:     Manage SSH keys registered with your GitLab account.
  user:        Interact with user
  variable:    Manage GitLab Project and Group Variables
  version:     Show glab version information

FLAGS
      --help      Show help for command
  -v, --version   show glab version information

```
