### ISSUE TITLE
Enforce best practices for melange YAMLs

### ISSUE THREAD

**Issue by imjasonh** [wolfi-dev/os#86]
- checked-in packages shouldn't depend on `packages.wolfi.dev/os` or include its keyring; packages are fetched from that repo and depended on locally during the build
- every melange YAML should have a corresponding entry in `Makefile` (would have caught https://github.com/wolfi-dev/os/pull/84)
- maybe harder to catch without involving `dag`: no duplicate package or subpackage names (would have caught https://github.com/wolfi-dev/os/pull/85)
- less importantly, consistently format YAML (mostly to avoid formatting arguments)
- more generally, melange could fail if it encounters an unknown field -- this would have caught the `epcho` bug fixed in #84

These checks should be enforced at CI time to prevent bugs from being committed.

This is complicated somewhat by the fact that melange YAML files aren't actually parseable YAML files, they're templates that get Go-templated into parseable YAML. Maybe we could templateize them then YAML-format them, or something else smart we haven't thought of yet.

**Comment by kaniini** [comment]
I have some thoughts based on updating `wolfi-secdb`, which caught a few things in #81.  I'm probably going to add a `melange lint` action, which can check some of these things, and then we can extend that into a wolfi-specific linting package.

**Comment by Dentrax** [comment]
> I'm probably going to add a melange lint action

Any ongoing work on this? I'd be nice to have a tracking issue for this in the melange side. If you split into smaller tasks, we are ready to help! @developer-guy 

Additional to @.imjasonh ideas, here are some other ideas:

* smoke test first: check if given file a valid `build.Configuration` struct
* check if `copytight.license` is correct (external api call needed to check LICENSE file, handling just GitHub would be fine in the first place)
* traverse all `target-architecture`, ensure melange have a support for each
* enforce `package.version` in semantic-versioning format
* `pipeline.with.uri` is correct URI format (not sure how to handle `${{ foo }}` stuff)
* `pipeline.with.expected-sha256` is correct sha256 format (do same for other algorithms)

**Comment by developer-guy** [comment]
It should be a separate command in the [wolfictl](https://github.com/wolfi-dev/wolfictl) CLI

**Comment by kaniini** [comment]
@Dentrax says he wants to work on this, so assigning it to him!

**Comment by rawlingsj** [comment]
@Dentrax have you started working on this?  I've got a need for a CI check so am thinking it best live in `wolfictl lint`.  If I make a start perhaps you can add extra lints to it once available?

**Comment by Dentrax** [comment]
Actual I already started on a branch to add a new `lint` subcommand to `wolfictl`, then couldn't find a proper time to implement _lint engine_. We'll (@developer-guy) get into it this week. We may request a help from you if we get stuck somewhere. Deal? 😇

**Comment by rawlingsj** [comment]
Do you want to PR what you have?  Even if it's just the structure and then we can both work on adding different linting together?  

Or maybe as soon as you do have the initial structure create a PR and we can add the different lints as followups?

**Comment by Dentrax** [comment]
Oh, sure definitely! We want to submit an initial PR as soon as we have some bare-minimum. (Which currently I don't have a one) So that we can start to work on adding _different lints_ collaboratively!

**Comment by Dentrax** [comment]
Here is, we (@developer-guy) submit the initial PR for implementing the `lint` subcommand! 🥳 https://github.com/wolfi-dev/wolfictl/pull/2 (Waiting your feedback.)
