### ISSUE TITLE
[Wolfi Package Request]: $PACKAGE_NAME

### ISSUE THREAD

**Issue by oultit** [wolfi-dev/os#9028]
### What software would you like us to add to wolfi-os. Ideally include a URL to the project and its source.

Chainguard Academy

### Please check all that apply

- [X] This package has an un-restrictive license
- [X] The package/versions proposed are actively maintained upstream
- [X] I am interested in adding this package to Wolfi OS myself
- [X] I am willing to help maintain this package

**Comment by ajayk** [comment]
Seems like a default template , nothing filled up closing this
