### ISSUE TITLE
Build npm from source 

### ISSUE THREAD

**Issue by ajayk** [wolfi-dev/os#9107]
Currently [npm](https://github.com/wolfi-dev/os/blob/main/npm.yaml) is built from copying the pre built npm from npm registry , instead build npm from source

**Comment by tuananh** [comment]
@ajayk I will give it a try if @rawlingsj is not available.

**Comment by tuananh** [comment]
@ajayk kindly help me review the PR https://github.com/wolfi-dev/os/pull/9708
