### ISSUE TITLE
busybox wget has different behaviour between arm and amd

### ISSUE THREAD

**Issue by rawlingsj** [wolfi-dev/os#9187]
To reproduce the error, we can run two containers, one arm, the second amd
```
docker run --privileged --platform linux/aarch64 --rm -it -v "${PWD}:/work" -w /work cgr.dev/chainguard/wolfi-base:latest
```
```
docker run --privileged --platform linux/amd64 --rm -it -v "${PWD}:/work" -w /work cgr.dev/chainguard/wolfi-base:latest
```

In each of them run `wget pear.php.net`

The results are different

arm:
```
wget pear.php.net
Connecting to pear.php.net (109.203.101.62:80)
Connecting to pear.php.net (109.203.101.62:443)
wget: note: TLS certificate validation not implemented
saving to 'index.html'
```

amd:
```
Connecting to pear.php.net (109.203.101.62:80)
Connecting to pear.php.net (109.203.101.62:443)
wget: note: TLS certificate validation not implemented
wget: TLS error from peer (alert code 40): handshake failure
wget: error getting response: Connection reset by peer
```

**Comment by rawlingsj** [comment]
This doesn't explain the difference in behaviours on both platforms but did see this https://github.com/wolfi-dev/os/blob/d2607fb882034652448e1adf1df785bb76f2f8da/busybox/busyboxconfig#L998

Wonder if this would help?

**Comment by kaniini** [comment]
busybox cannot depend on openssl, as openssl needs busybox to build.  solution is actually to provide an ssl_client binary which proxies to openssl.

**Comment by rawlingsj** [comment]
TBH, I'm not sure how to do that is this something you could help with?

**Comment by kaniini** [comment]
Yeah I can do it!

**Comment by xnox** [comment]
> busybox cannot depend on openssl, as openssl needs busybox to build. solution is actually to provide an ssl_client binary which proxies to openssl.

this is factually incorrect. There is no build-dependency or runtime-dependency loops between openssl and busybox in any form. Busybox openssl feature doesn't link against libssl, it simply has code to exec `/usr/bin/openssl`. Most distributions that enable this feature, do not even add any runtime depends or recommends on openssl client utility.
And separately openssl can be built without busybox (non-full) or coreutils. Thus enabling openssl feature in busybox doesn't create any bootstrapping concerns.
