### ISSUE TITLE
Add Rust package

### ISSUE THREAD

**Issue by patflynn** [wolfi-dev/os#93]
Details TBD

**Comment by Lunarequest** [comment]
will someone be taking this up or could i take a shot at this?

**Comment by kaniini** [comment]
If @Lunarequest wants to do it that’s fine by me :)

**Comment by Lunarequest** [comment]
> If @Lunarequest wants to do it that’s fine by me :)

I'll take a shot. Btw is there anyway to test building a package without building everything

**Comment by kaniini** [comment]
You can do `make packages/foo` to only build foo.  Eventually we will use dag to drive the build.

**Comment by Lunarequest** [comment]
does one need to run `make` and build everything before you can use `make packages/foo` or is there some sort of prebuilt repo we can use?

**Comment by kaniini** [comment]
You can pull down the prebuilt packages with gsutil.  See the CI pipelines for how to do it.

**Comment by Lunarequest** [comment]
The following packages need to be added to build rust from source

1. wasi-libc
2. libssh2{,-dev}
3. libgit2{,-dev}

I'll add these today evening and open a pr with them

**Comment by tuananh** [comment]
similiar to my issue with zip file maybe? https://github.com/chainguard-dev/melange/pull/166

**Comment by Lunarequest** [comment]
I think what's happening is tar is being used for all files and tar obviously can't unpack zip files, and it may not be built with support for xz compressed files so you end up with tar complaining about invalid magics

**Comment by rawlingsj** [comment]
For when you don't want to automatically untar you can use a fetch property `extract: false` and uncompress yourself, for example
https://github.com/wolfi-dev/os/blob/aa93d4401e39589da8a9ff02177dc2486fcdb94e/bazel-5.yaml#L24-L29

**Comment by Lunarequest** [comment]
Which package provides llvm-config?

**Comment by tuananh** [comment]
> Which package provides llvm-config?

i believe that would be `llvm15-dev` IIRC

**Comment by Lunarequest** [comment]
I've made a draft pr at #138 its blocked by LLVM missing the FileCheck variable

**Comment by kaniini** [comment]
Rust has been packaged, this can be closed.
