### ISSUE TITLE
Repo guidelines

### ISSUE THREAD

**Issue by amouat** [wolfi-dev/os#94]
It would be nice to add some rules and guidance for what should go in this repo.

In other words what is considered non "os"? Would nginx be allowed here? Wordpress? Why?

**Comment by luhring** [comment]
My understanding is:

`wolfi-dev/os` -> the distro itself, i.e. the universe of Wolfi packages that we provide.

`wolfi-dev/<anything else>` -> ancillary tools/data that helps us maintain and provide the packages in `wolfi-dev/os`; e.g. `dag`, `secdb`

**Comment by kaniini** [comment]
what @amouat is proposing is that we need a second repository for "extras" that don't make sense to include in this universe, like Wordpress.

**Comment by kaniini** [comment]
I was going to say `extras` but yeah.  Same idea.

**Comment by kaniini** [comment]
> Just for my orientation, what doesn't make sense about including Wordpress in wolfi-dev/os?

Most people don't want to manage wordpress with a package manager.  Alpine does have some PHP applications in `community` though, so it could make sense for `extras`, I guess.
