### ISSUE TITLE
[Wolfi Package Request]: java-snappy-native

### ISSUE THREAD

**Issue by mpanov** [wolfi-dev/os#9659]
### What software would you like us to add to wolfi-os. Ideally include a URL to the project and its source.

Main repository we used to get library installed:
https://pkgs.alpinelinux.org/packages?name=java-snappy-native&branch=v3.17&repo=&arch=x86_64

Link to the Project: https://github.com/xerial/snappy-java

### which versions of the software should we include?

latest

### Add some justification for why this specific package and versions are important.

This library was needed to fix Runtime exception occurred in the service accessing GCS bucket

Exception:

# Caused by: java.lang.UnsatisfiedLinkError:
#  /tmp/snappy-1.1.10-4949df66-9a5f-4527-acb5-991c2889578d-libsnappyjava.so:
#  Error loading shared library ld-linux-x86-64.so.2: No such file or directory 
# (needed by /tmp/snappy-1.1.10-4949df66-9a5f-4527-acb5-991c2889578d-libsnappyjava.so)

### Please check all that apply

- [X] This package has an un-restrictive license
- [X] The package/versions proposed are actively maintained upstream
- [ ] I am interested in adding this package to Wolfi OS myself
- [ ] I am willing to help maintain this package

**Comment by mamccorm** [comment]
This package was added wolfi as part of the following commit:
- https://github.com/wolfi-dev/os/pull/9925
